app/assets/stylesheets/components/shared.scss, app/controllers/page_version_controller.rb, app/models/page_version.rb, app/views/page_version/show.html.slim
Currently the page version screen lets users view a version and see both the state of the page at that version and the differences with the previous version.  The University of Texas wants to be able to see the differences between one version with any other version, not just the previous one.
I've implemented the base functionality, but we need to make this more visually appealing.  Ideally, the select list for the comparison version would appear at the header of the `diff` view, where I have added the text *Form goes here*.  This would serve the two purposes of 1) showing the user which version was being compared, and 2) allowing them to select a different version to compare against.
So the final behavior should be:
* Users may select from the existing list on the left column and see …
=> Implemented #264 by adding a form.  Further UI work needed

app/views/shared/_page_tabs.html.slim
Check to see if the user is signed in before checking their access to the transcribe tab.
=> Issue #435, bug in transcription tab access

app/controllers/application_controller.rb, app/controllers/registrations_controller.rb, app/controllers/transcribe_controller.rb, app/views/layouts/application.html.slim, spec/features/guest_spec.rb, spec/features/role_view_spec.rb
When a user first signs up, they should be redirected back to the page where they were when they clicked the sign up button.
=> #627 New user sign up and redirect

app/models/sc_manifest.rb, db/migrate/20170523151631_change_label_size_in_sc_manifests.rb, spec/features/add_data_spec.rb, spec/features/needs_review_spec.rb
Just FYI: I have the limit in the migration, but it looks like mysql won't actually let you set a limit on a text field, but strings can't be longer than 255 characters.  So the field is big enough for anything now, but doesn't have a 512 limit.
=> #662, Label field length in IIIF imports

app/helpers/add_work_helper.rb, app/helpers/error_helper.rb, lib/tasks/ingestor.rake
I set up a module for SMTP error handling, to prevent the uploads from failing if there's something wrong with the SMTP configuration.  Right now it's only applied to the document uploads (in both the document upload process and the rake task), but it could be applied to other SMTP code if needed.
=> #682 - Uploads failing on SMTP errors

spec/features/add_data_spec.rb, spec/features/admin_view_spec.rb, spec/features/check_upload_spec.rb, spec/features/document_sets_spec.rb, spec/features/url_spec.rb, spec/features/zz_convention_spec.rb, spec/features/zz_deletion_spec.rb
Tests are only dependent on add_data_spec.rb - that needs to be run first, but then the rest of the tests can be run independently.
=> Reorganized tests to decrease dependencies

app/views/layouts/application.html.slim, config/routes.rb
Added routes and path helpers for the static pages, because Rails couldn't locate them from the Devise controller.
=> #783 static links

app/controllers/iiif_controller.rb
As promised in #847: this PR uses the width and height dimensions from a `Page`'s linked `ScCanvas` if the page has no recorded dimensions. I first used `if/then/else` but later found a more concise way to do the same was already in use elsewhere in the file, hence two commits.
I apologise for the extra (automatic) edits that remove whitespace that make this commit bigger – the actual edit is on line 307.
=> Use ScCanvas dimensions when Page dimensions don't exist (fixes #847)

app/views/shared/_iiif_div.html.erb
This fixes #569 for me.
In our 'test production' environment, I `rake assets:precompile` the assets, including OpenSeaDragon's assets (images and JavaScript). That means images get filenames with a file hash included, although the OSD JavaScript does not know about the changed names. (It was looking for the files in the correct path, but the filenames didn't match.)
This PR overrides the navigation images, image by image, during OSD initialisation. Because the default `prefixUrl` is `/images/`, I made it the empty string.
The indentation weirdness is due to a mix of tabs and spaces in the existing code.
=> Set OSD navigation images path in ERB, prefixUrl to empty string (fixes #569)

app/controllers/application_controller.rb
The request for the IIIF transcription was being redirected by the authentication.  This fixes that problem.  I don't think we have tests for the IIIF API, so other calls to it should be manually tested.
=> #974 - updated authentication for iiif requests

app/controllers/iiif_controller.rb
This is the first half of the Rerum Inbox work, adding canvas pointers to the annotation layers FromThePage exports, so that they'll work as a stand-alone document.
I'd like to deploy this soon, then add the actual call to the Rerum Inbox API later after further discussion.
=> Rerum inbox

app/models/sc_manifest.rb
This is necessary for Qatar Digital Library's language-coded manifests.  I was not able to test it with a truly multi-lingual document.
=> Flatten multi-lingual labels for #1002

app/views/user/profile.html.slim, app/views/user/update_profile.html.slim
For Issue #958
* Removed `Location` from user profile view and update form
* Removed required fields note from user profile update (there's only one field)
* Retained `Location` for owner profile
* Retained required fields note for owners
=> #958 Removed location field from user profile

app/models/ia_work.rb
=> Truncate overlong titles imported from IA

app/views/devise/registrations/new_trial.html.slim
#1048 Changed trial wording from 'two weeks' to 'two hundred pages'; added link to kickoff call
=> #1048 Changed trial registration wording

app/assets/stylesheets/base/global.scss, app/views/transcribe/assign_categories.html.slim
#1073 
I wasn't expecting this one to be a one-liner! Here's what it looks like:
A couple things:
- I feel like using the `page.source_text` content makes for a rather busy display (showing other sets of brackets, etc.), but because we are matching on the `article.title` we can't use `page.search_text`, since the titles don't always match the display text. Also, I suppose it actually is useful to include both the canonical subject title as well as the displayed text so the user can see what s/he is linking.
- Since the context goes forward and backward, I went ahead and put it on its own line. I tried to strike a balance between being able to quickly identify the word in the context (by highlighting it), and trying to keep it from dominating the page (mono-font, not too big, etc.)
If we …
=> Add context to `assign_categories` view

app/controllers/iiif_controller.rb
Since the IIIF server API was built before the Internet Archive supported IIIF
it did not expose any Internet Archive content.  Now it re-presents IIIF canvases
and works, so an IA work can be imported into FromThePage, transcribed, and
then viewed in IIIF clients like Mirador.
=> Internet Archive imported works now support IIIF API

app/controllers/article_controller.rb, app/controllers/category_controller.rb, app/models/article.rb, app/models/category.rb, app/views/article/edit.html.slim, app/views/article/list.html.slim, app/views/category/add_new.html.slim, app/views/category/edit.html.slim, db/migrate/20180516132442_add_article_lat_long.rb, db/migrate/20180516133319_add_categories_gis_enabled.rb, db/migrate/20180517150605_add_article_uri.rb, spec/features/linking_spec.rb, spec/features/owner_actions_spec.rb
Issue #1061
* Adds Lat/Lon to subject/article table
* `DECIMAL` type to allow for specific decimal precision
* Lat: validates between -90/90; Lon validates to -180/180; null allowed
* Includes `gis_enabled?` method to determine if any related categories are GIS enabled
* Conditionally displays Lat/Lon fields on subject/edit view based on `gis_enabled?`
* Fixed form validation error on subject/edit form
* Adds `gis_enabled` to category
* Defaults to `false`
* Enabling/Disabling GIS through "actions" menu affects all descendant nodes in tree
* Changed "rename category" to "edit category" and added "Enable GIS" setting
* Added "Enable GIS" to create category form
* Adds URI field to all subjects
=> Adds Lat/Lon option to categories

app/helpers/abstract_xml_helper.rb, app/models/xml_source_processor.rb
This fixes the hyphenation display problems described in #1090.
Adding the hyphen to views where the `lb` was significant was fairly straightforward, but I did end up changing the semantics of the outputted HTML. The original code used `Element.new('span')` and replaced the self-closing `<lb />` tags. for whatever reason, REXML replaced those line breaks with "self-closing `span`s" which, of course, aren't a thing. As a result, the browser was closing these tags automatically, which ended up making the new `span`s nested. Adding the text `''` to the span element forced the closing tag. More importantly, the hyphen itself is contained within `span.linebreak` as well as the `<br />`. Again, the semantics are a little weird, but I think this is an OK way of doing things. In the cases where …
=> Hyphenation for #1090

Gemfile, Gemfile.lock, gemfiles/Gemfile.mysql57
Specified `autoprefixer` to the latest 8-dot version in both the main `Gemfile` (and `.lock`) and the `mysql57` `Gemfile`.
I also updated the `mysql2` gem in the main `Gemfile`. Turns out, it had been updated in the other one. This should also take care of #1115
=> Specified and fixed Gem versions

app/views/transcribe/assign_categories.html.slim, gemfiles/Gemfile.mysql57
Makes context three lines. See the discussion on #1073.
I had to replace `\n` with `<br />` because `.excerpt()` strips newlines.
=> Expanded subject categorization context to three lines

app/controllers/iiif_controller.rb, gemfiles/Gemfile.mysql57
Following the logic in adding links to `seeAlso` for Manifests, I appended `, :only_path => false` to the calls for URLs for `related`. This should fix #1030.
=> Include host in IDs for related items in IIIF

app/controllers/iiif_controller.rb, gemfiles/Gemfile.mysql57
This fixes #1123 by giving `oa:commenting` as `motivation` to the Osullivan library when a new Annotation is created. (This overrides the default value `sc:painting`.)
=> Set oa:commenting as motivation for notes

app/controllers/transcribe_controller.rb, app/models/collection.rb, app/models/document_set.rb, app/views/collection/edit.html.slim, db/migrate/20180826201612_add_default_orientation_to_collection.rb, db/migrate/20180826214652_add_default_orientation_to_document_set.rb, db/schema.rb
Closes #787
Allows collection owners to set the default orientation of their project.
The default is '"Page on the Left"
Unless it is a field-based project, in which case it defaults to "Page on the Top"
Unless the user has a cookie set, in which case it follows the user.
=> Set default collection orientation

app/controllers/transcribe_controller.rb, app/views/shared/_page_tabs.html.slim
Closes #1084 
Hides the navigation buttons on both transcription and translation preview views by setting a `display_context` flag in the controller. All of these displays rely on a long-is set of `if-else` statements that branch based on parameters set in the `POST` req. This seemed like the cleanest way to operate within that paradigm.
=> Disable pagination in transcription previews

app/views/shared/_iiif_div.html.erb
Closes #1193
Set it to `10` for no specific reason. I didn't notice a terribly adverse UX by using such a high number.
I suppose we could make this a setting in the `work` if it becomes distracting for higher-res images, but I doubt that'll be necessary.
=> Openseadragon `maxZoomPIxelRatio`

app/views/export/index.html.slim
Resolves #1190 
I've added the link to the API doc to the bottom of the `/export` page for issue #1190. In the process, I removed trailing whitespace from two lines in the `export/index.html.slim`, since my text editor does this automatically. I see that html.slim is whitespace-sensitive. I have not seen an issue with the removal of these particular trailing whitespaces on this page. Do you foresee this as a problem?
=> 1190 link to api documentation

app/views/export/index.html.slim
Resolves #1188 by moving the sections "Export Subject Index" and "Export All Tables" down below the table of individual exports.
=> Moves subject and table exports down to bottom in original order

app/controllers/export_controller.rb
Closes #1164 
Adds Contributors and Notes to table export.
Contributors are in the format `Name<email@address>` and delimited with pipes.
Notes are in the format `[Name<email@address>]: Note` delimited with pipes. Notes are sanitized by replacing pipes with `//`; White space is stripped and replaced with `.gsub(/\s+/, ' ')`
=> Adds contributors and notes columns to table export

app/views/article/show.html.slim
Resolves #1195 
It displays this line only if an `article.uri` is present.
=> 1195 show subject uri on overview

app/controllers/admin_controller.rb, app/views/admin/index.html.slim
Closes #1249 
This PR changes a number of `Model.all` queries (which were only used for their `.length` property to `Model.all.count`.
Additionally, it gives the `@owners` variable its own query using `.where` rather than filtering `User.all`. This should help leverage ActiveRecord's caching and lazy querying where possible (e.g., pagination).
=> Admin dashboard performance improvment

.travis.yml, travis/.travis_mysql57.sh
Closes #1287
I was getting test failures on all the Travis environments that needed the `mysql57.gemfile`. I was pleasantly surprised to realize these failures were because we removed support for MySQL 5.7 and had deleted the old gemfile. 
So, I removed any environment that was looking for the old gemfile (since it's not tehre any more). Perhaps there was a reason why this hadn't been done... I figured it was a 5min fix for me either way.
=> Remove MySQL 5.7 Tests from Travis

app/controllers/collection_controller.rb, app/views/collection/_contributors_body.html.slim
Closes #1280 
TODO:
This PR adds the ability for collection owners to export collaborator activity, scoped to a particular date range.
The generated CSV file includes the following for each `Deed`:
1. A timestamp
2. User `display_name`
3. User `email`
4. Deed Type
5. Page Title
6. Page URL
7. Work Title
8. Work URL
In addition, this PR makes some minor adjustments to the layout of the old "veiw activity" link and standardizes the long lists of Users to use `<br />` rather than `<p>` in the interest of density.
OLD:
NEW:
OLD: 
NEW:
=> Export Collaborator Activity Stream

app/controllers/application_controller.rb
Closes #1314 
Per the issue note, I was able to remove the explicit call to track the visit in the application controller. I tested this on my machine and it seems to work. There still seems to be an ahoy visit being logged (I think?)
=> Fix Ahoy duplicate entry errors

db/migrate/20180205190722_update_notifications.rb, db/migrate/20180525105752_save_callbacks.rb, db/migrate/20190515191553_incompatibilities_20180205190722.rb
This needs to be merged into `master` before we can upgrade Fordham.
After upgrading, we should run another backup and then run
`truncate table ahoy_events;`
`truncate table visits;`
We should also disable guest logins.
=> Reordered scripts to upgrade Fordham's installation

app/controllers/admin_controller.rb, lib/tasks/clean_anonymous_ahoy.rake
On deploying this, we need to set up a cron job that does the following:
`rake fromthepage:clean_anonymous_ahoy`
=> Delete old anonymous ahoy records

spec/models/deed_spec.rb, spec/spec_helper.rb
Closes #1363 
The problem was that the factories that we are using to stub the deeds were (intentionally) having to be saved to the database, which triggered the `before_save` hooks. Because we are prerendering deeds, the application was trying to prerender the stubbed deeds, which lacked the necessary properties for the partial.
The solution was simply to mock the class methods in the tests, like so:
allow_any_instance_of(Deed).to receive(:calculate_prerender)
allow_any_instance_of(Deed).to receive(:calculate_prerender_mailer)
and that solved the problem.
I've also silenced the `reassigning constant` warning that we always get in the tests (because the SMTP settings are by default set to `false`.
=> Fix deed_spec issues

app/controllers/transcribe_controller.rb, app/models/xml_source_processor.rb, spec/features/disable_subjects_spec.rb, spec/models/xml_source_processor_spec.rb, spec/spec_helper.rb
Closes #1277 
I was able to accomplish this without completely refactoring the `wiki_to_xml` method into two. In fact, the final solution turned out to be quite simple. I was really hesitant to make any significant changes to this section because of how core this functionality is; we didn't have any tests, so I couldn't feel confident I wasn't regressing.
But, we have some tests now. One minor change I made was to change the method signature to accept the whole page object rather than only the wiki text. This allowed a more clean way to reference the page's collection object in order to determine if subject linking was disabled.
The Unit tests are simple; they basically just test that the XML output is what we expect. I had to assume that the former functionality was correct, but this …
=> Export formatting for works with indexeing disabled

app/assets/javascripts/application.js, app/assets/javascripts/plugins/jquery.litebox.js, app/assets/stylesheets/base/customer_color_scheme.scss, app/assets/stylesheets/base/ftp_color_scheme.scss, app/assets/stylesheets/base/global.scss, app/assets/stylesheets/base/helpers.scss, app/assets/stylesheets/components/buttons.scss, app/assets/stylesheets/components/layout.scss, app/assets/stylesheets/components/litebox.scss, app/assets/stylesheets/components/shared.scss, app/assets/stylesheets/sections/deed.scss.erb, app/assets/stylesheets/sections/home.scss, app/assets/stylesheets/sections/page.scss, app/helpers/application_helper.rb, app/views/admin/uploads.html.slim, app/views/admin/user_list.html.slim, app/views/article/list.html.slim, app/views/collection/edit.html.slim, app/views/dashboard/_new_work.html.slim, app/views/dashboard/_owner_header.html.slim, app/views/dashboard/landing_page.html.slim, app/views/dashboard/omeka.html.slim, app/views/document_sets/_set_works.html.slim, app/views/document_sets/index.html.slim, app/views/document_sets/settings.html.slim, app/views/ia/manage.html.slim, app/views/layouts/application.html.slim, app/views/user/_owner_profile.html.slim, app/views/work/edit.html.slim
Closes #1346 
The email about accessibility compliance lists three things for us to look at. Contrast, Form Labels, and Language attributes.
I worked hard on this, but without the ability to run it through the (paid) linter that they used, I was stuck clicking around the site looking for errors. So, perhaps after merging this, we may ask UT to run it again? 
I tried to be as light-handed as possible making these edits. Where I had to be more aggressive, I tried to maintain the look and feel of the site as best as I could. The two "major" changes I made (viz. more than just tweaking the text-color to be a bit darker) were to the Deed label coloring and to the transcription preview/autolink buttons.
I *think* I've got a good label for all form elements. I confess, I'm not sure that I looked …
=> Accessibility Compliance

app/models/page.rb, spec/features/collection_spec.rb, spec/features/editor_actions_spec.rb, spec/models/page_spec.rb
Closes #1274 
This change resets the status of a page to `nil` when the `source_text` is empty and the page status is not marked `STATUS_BLANK`.
I've implemented this only for the `transcribe` case, an not for the `translation` case. This has to do with the fact that I don't fully understand how to reason about the the page status when, e.g., the transcription is blank, but the translation is done. This matters now, since we have an explicit `image -> translation` workflow.
Probably one more reason to come up with a more flexible schema for pages that allows for different page-text-types (transcription, translation (multiple versions), normalized texts, etc.); then each of those can have a specific `text_status` that contributes to an overall `page status`. That will probably make our …
=> Reset page status when transcription is empty

app/models/work_statistic.rb, spec/features/collection_spec.rb
Closes #1351 
As far as I was able to tell, at no point did the `Work` ever call an update function on the `Collection`. That said, there already existed a function that seemed to be intended for this purpose (`recalculate_parent_statistics`), which was (as far as I could tell) never invoked in our code.
So, I put a call to that function (which updates both parent collections and document sets) whenever the work stats are updated. Since the work stats seem to be working fine, this seemed like a solid place to put this code.
My one reservation with this PR is that I was running into a situation where it seemed like perhaps I was dealing with a DB race in the test. I'd query the DB and ask for the `ptc_completed` and it would always give me `0` (rather than `100`). But, when I'd go into the …
=> Collection stats not updating

app/controllers/notes_controller.rb, app/views/notes/_note.html.slim, app/views/notes/_notes.html.slim
Closes #1375 
This PR allows users to submit multiline notes. It uses the `simple_format` rails helper in conjunction with the `sanitize` helper. It does not change how the notes are saved in the DB; this only affects how the note is displayed.
The one problem I had was that the `update` function was only handled on the client, which made it so edited notes  wouldn't be processed by these same functions. The old update function simply returned a `204` code and left it to the client to render the change. In the new version. the server returns a success code and a re-rendered partial of the note, which then replaces the old version of the note.
=> Allow multiline notes

app/controllers/dashboard_controller.rb, app/models/collection.rb, app/models/document_set.rb, app/views/dashboard/_alphabetical_collections_and_document_sets.html.slim, app/views/dashboard/collections_list.html.slim, app/views/user/_owner_profile.html.slim
This is my first attempt with trying to fix some of the performance
issues described in #1175.
While show_to? isn't the problem, I am still hoping that this helps to
reduce complexity.
Unfortunately some methods we use depend on collections and document
sets being iterated (which is the expensive part), so just move that
code to collections_list for now.
=> dashboard: remove the call to show_to? from collections view

app/views/devise/registrations/new.html.slim
Closes #1424 
At present, this PR is just a patch so that new `owner` registrations will still carry through if they get some validation errors. 
We are losing the owner signup flow because the hidden field `is_owner` isn't a part of the normal `new_user` form. Because it is the `new_user` form that gets displayed with the validation errors, the hidden `is_owner: true` field is getting wiped out and the registration becomes a normal collaborator registration.
I've added the `is_owner` (and `paid_through`) hidden fields to the normal user registration view. They default to `false/nil` (respectively), so normal registrations aren't affected. However, when a new `owner` gets validation errors, the (wrong) `new_user` form is still displayed but the hidden fields are properly populated with …
=> Fix for keeping owner signup flow with validation errors

app/controllers/application_controller.rb, config/initializers/ahoy.rb, spec/features/ahoy_spec.rb
Closes #1314 
I think I figured this out. 
First off, I added a spec test for logging Ahoy visits, so we will be alerted to regressions. And on that theme, this PR does not regress, as the last one did.
The problem with the duplicate entries is related to the fact that in the `ApplicationController` we were calling `track_visit` for every request. This method seems to be the one that *initiates* a visit, so it was trying to insert the `current_visit` into the DB for every request. Obviously, this is what was giving us the MySQL errors.
Our first attempt to fix this simply removed that code (see #1366). The result was that *no* visits were tracked.
After reading the (sparse) documentation for v1.6.1 of the gem (which we are using), there was no indication that we should have had to add any …
=> Too many ahoy errors, again

app/views/display/_pages_view.html.slim
Closes #1379
As we do in the page#read,transcribe and preview views. This is important for displaying RTL languages properly in the work-page view. Note the RTL justification in the latter image.
**Before**
**After**
=> Apply langauge attrs to the page view

app/assets/stylesheets/components/layout.scss, app/views/layouts/application.html.slim
Use a list and flexbox to rearrange links and copyright notice
accordingly (so that they fit on a small footer).
Fixes: #1439
=> layout: make footer smaller

app/controllers/document_sets_controller.rb
Closes #1425
The DocSet controller seemed to not have any authentication logic whatsoever. I borrowed the auth logic from the `collection_controller` and restricted all but the index method.
=> Restrict document set routes.

app/assets/stylesheets/sections/page.scss
margin-top causes the textarea to overlap with the "Save Changes" button
(when transcribing a lengthy document), making the button unclickable.
Removing the CSS property fixes the issue.
Fixes: #1437
=> transcribe: fix save button bug

app/controllers/registrations_controller.rb, app/models/deed_type.rb, app/models/user.rb, app/views/deed/_deed.html.slim, spec/factories/collection.rb, spec/features/devise_spec.rb, spec/models/deed_type_spec.rb
Closes #1370 
This PR adds the `Collection Joined` Deed Type and automatically has new users "join" a collection based on where they entered the site.
Although the `Ahoy::Visit` does include a `landing_page` field, I couldn't figure out a good way to parse the path to determine whether it was, in fact, a path that included a `Collection`. As a way around this, I've opted to use the oldest `Ahoy::Event` from the `current_visit`. Ostensibly, this gives the same data, since the first `Event` of a `Visit` includes, by definition, the landing page. The advantage of using the `Event` is that it provides`Controller#method` as well as the URL parameters. So, we can check to see if this `Event` includes a `collection_id`, and if so, we can pass it to the `join_collection` method on the `User`, …
=> Join collection on signup

app/controllers/user_controller.rb, app/models/document_set.rb, app/models/user.rb, app/views/dashboard/_alphabetical_collections_and_document_sets.html.slim, app/views/dashboard/_hierarchical_collections_and_document_sets.html.slim, app/views/user/_owner_profile.html.slim, spec/factories/collection.rb, spec/factories/document_set.rb, spec/factories/user.rb, spec/features/collaborator_spec.rb
Closes #1196 
Closes #1435 
This PR addresses the way that we display collections and document sets on owner profile pages. Formerly, only public collections and docsets would show up on the owner profile pages, regardless of whether the current user is a collaborator.
Importantly, this PR only addresses whether a collection or docset is *displayed* and not whether a given user can make edits (those permissions are working as desired, as far as I know).
After some discussion, we clarified the specific functionality for all combinations of private/public collection/docset for public/collaborator viewing (tests included). The truth table (the feature tests follow this format):
1. When Collection and DocSet are both public, non-owners should see them.
2. When Collection is private and Docset …
=> Owner profile page collection and docset visibility

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/initializers/rack-mini-profiler.rb
Currently this just adds the Bullet and Rack-Mini-Profiler gems to the gemfile with no configuration.
The RMP gem "just works" in the development environment, but the Bullet gem requires some config in the `development.rb` initializer. We `.gitignore` that initializer, however, so we'll need to either need to check it back in or just configure it for ourselves (I'm inclined toward checking it back in, personally).
I've opened  #1485 to address configuring RMP for use in production environments.
=> Added Bullet and RMP

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/dashboard_controller.rb, app/helpers/dashboard_helper.rb, app/models/collection.rb, app/models/document_set.rb, app/models/document_set_work.rb, app/models/user.rb, app/models/work.rb, app/views/dashboard/landing_page.html.slim, db/migrate/20190906201041_add_collection_and_document_set_counter_cache_cols.rb, db/schema.rb, spec/spec_helper.rb
Closes #1493 
This addresses the slow `dashboard#landingpage` (where the "Find A Project" button takes you as a guest performance.
This route had two major problems:
1. Querying for the relevant collections and docsets used a couple `.map` operations which fired off N+1 queries.
2. Collection rendering was also exhibiting N+1
**Results**: ~240 queries per page load, total time to render ~2.5 seconds
The Collection/Docset rendering was slow do to the fact that we were not only *not* eager loading, but, when references to a particular Collection's `owner` were used (e.g., in `link_to`), they were accessed through the inverse relationship that they were queried from. In other words, when we are looping through `@users as |user| , then looping through `user.collections as |collection|`, we …
=> Improve dashboard#landing_page route perf

app/controllers/document_sets_controller.rb, app/views/document_sets/_edit.html.slim, app/views/document_sets/new.html.slim
I originally misunderstood how this route worked. The page under consideration should only be able to be edited by people with *collection*-level owner permissions. This is the right way to fix that page's permissions errors.
=> Proper handling of docset auth

app/assets/stylesheets/components/layout.scss
When browsing the site from a mobile phone, the text inside .footer_nav
will look centered and out of place compared to when browsing from a
computer with a larger screen.
Set text-align: left on .footer_nav to fix this issue.
This improves on #1457.
=> layout: fix footer text alignment

lib/tasks/nightly_user_activity.rake
only those who enable "Nightly email with activity in collections you've
worked on" (user_activity) in their own profiles.
Fixes: #1443
=> nightly_user_activity: don't email opt-out users

lib/contentdm_translator.rb, spec/http-mocks/cdm/digitalindy_org.yml, spec/models/contentdm_translator_spec.rb
Closes #1503 
This PR adds the ability to use vanity URLs for importing CONTENTdm items.
The core logic of the CDM translator I left untouched, but I added a helper function to extract the appropriate CDM host. If the given URL's host is a proper CDMhost, the server (e.g., `cdm1234`) is returned immediately. If the host is not a valid CDM host, then the function makes a call out to the expected URI for the root IIIF manifest of the repository. If the returned JSON `@id` exists and is a good CDM host, we return the server as above. Otherwise, return nil.
The logic proceeds as before from there.
I've included tests for Repository, Collection, and Item level vanity URLs.
=> CONTENTdm vanity urls

app/views/collection/edit.html.slim, spec/features/collection_spec.rb
rather than "display_name - email", otherwise the layout breaks.
Fixes: #1544.
=> collection: display name

app/controllers/transcribe_controller.rb, spec/features/editor_actions_spec.rb, spec/features/needs_review_spec.rb
Closes #1507 
~~A two-liner. We were just redirecting to the wrong route.~~
True to form, this is actually more complex than we thought.
We allow users to "mark page blank" from the reading view, which means we need to redirect to either the reading view or the transcribe view depending on where the user came from.
I've added an option with a default value to the `mark_page_blank` method that conditional sets the redirect path. All the early return stuff in the `save_transcription` and related methods made me uneasy about doing much refactoring.
=> Mark blank redirect to transcribe view

app/assets/stylesheets/sections/home.scss, app/views/static/splash.html.slim, config/initializers/slim.rb
I've noticed a few bugs on the home page, this PR fixes them.
1. Fixed broken intro box layout on a tablet:
2. Fixed layout of the Advantages and Feedbacks sections:
3. The above bug was appearing only in production (in development it was ok) and it was caused by minification of the html in production. So I've turned the minification (or, to be exact, turned off pretty html formatting) in development mode to find out similar issues (if any) during development.
4. Added number formatting for the Pages Transcribed:
=> Home page fixes

app/models/work.rb, app/views/dashboard/owner.html.slim, app/views/layouts/application.html.slim
This allows sites to not have defined the intercom tokens in their 01fromthepage initializer.
=> Decouple Intercom further for master branch

app/views/collection/edit.html.slim
Blank Collection can take a long time on a large collection, let's alert
the user before we trigger it.
=> collection: add confirm alert

lib/contentdm_translator.rb
This is not an ideal solution, as we'd really prefer to read the FTS field and use that.  Unfortunately, that configuration information is only available via the CDM SOAP API, which requires passwords and logins which are not part of our import UI.
=> Address #1720 by pulling from  field.

app/views/article/show.html.slim, public/robots.txt
This both adds `rel="nofollow"` to the problem links and modifies `robots.txt` to ban the URLs entirely.
=> Keep crawlers from launching full-text searches

config/routes.rb
This fixes an issue I was running into running on the rails6 branch. I'm not sure if it is the correct fix but it works as far as I can tell. Previous to this fix, adding a category to a subject would fail with: ActionController::RoutingError (No route matches [POST] "/article/article_category"):
=> Update article_category route

app/models/page.rb
If a work becomes completely transcribed but then later a page within that
work becomes untranscribed, `next_untranscribed_page` never gets updated.
This causes the work to be missing from some views where works with
untranscribed pages are listed.
This change causes `update_next_untranscribed_pages` to also be run if
`next_untranscribed_page` is currently `nil`. This was tested by completing a
work, subsequently deleting a transcription for a page, saving, then
verifying in the database that the column went from null to the correct
id.
=> Expand scope of update_next_untranscribed_pages

app/controllers/admin_controller.rb, app/controllers/user_controller.rb, app/views/admin/edit_user.html.slim
This fixes a bug where neither users nor admins could update the real name
of a user profile. The `user_params` permit list had `:display_name`, however,
per the model that is an auto-generated field and `:real_name` is the one
used in the form.
This has been tested and verified to work correctly now.
=> Update user_params filter to use real_name

app/controllers/admin_controller.rb, app/views/admin/edit_user.html.slim
The display_name field is intended to be auto generated and leads to
unexpected behavior for the user when it is modified. This removes the
display_name form field from the edit_user form and the user_params permit
list. This also adjusts the real_name form field to have the top-of-form
styling that display_name previously had.
Signed-off-by: Jacob Creedon <jcreedon@gmail.com>
=> Remove display_name from admin edit_user form

app/controllers/admin_controller.rb
when the admin edits an owner they are redirected to the owner tab instead of the user tab
=> 1645 redirect to owner tab

app/views/collection/show.html.slim, app/views/display/_multi_page.html.slim
buttons like "start transcribing," "pages that need review," "pages that need indexing," etc will not show up for the transcriber if the collection is inactive
=> inactive projects will not have transcribing buttons

app/views/user/profile.html.slim
For some reason, some notes are not being deleted with the pages they are on are deleted.  (This seems rare, and may only happen when an individual page is deleted from a work; the example problem showed a note on a missing page, but with an existing work and collection, so the work had not been deleted.)
When we try to display a user's activity and their recent notes, the profile display was blowing up because of a nil page.
Closes #1898
=> Orphan notes explode on display of (missing) page title

app/controllers/registrations_controller.rb, app/controllers/transcribe_controller.rb, app/controllers/work_controller.rb
Several controllers did not have permitted parameter statements.
This affected
saving page titles
saving most work settings
adding a name to a new user on the registration form
This fixes #1911 and fixes #1913 as well as the registration form problem.
=> Fixes #1911 and Fixes #1913 by permitting params

.travis.yml, app/models/xml_source_processor.rb, spec/features/collection_spec.rb, spec/models/xml_source_processor_spec.rb
This fixes #1875 (and potential other bugs caused by illegal characters) by replacing characters that are outside the [valid range for XML 1.0](https://www.w3.org/TR/xml/#charsets) with a space. I chose to replace with space rather than remove because someone might use some characters as spacing – and it could signal that there used to be an invisible character where there are unexpected spaces.
I ran a simple test to see that form feeds are replaced, as well as `NULL` characters, using:
```ruby
puts "blabla\fdljlkdf\tcheck\0".gsub! /[^\u0009\u000A\u000D\u0020-\uD7FF\uE000-\uFFFD\u10000-\u10FFFF]/, 'REPLACED'
#=> "blablaREPLACEDdljlkdf   checkREPLACED"
```
I didn't dare to touch the test spec `spec/models/xml_source_processor_spec.rb`, as I don't really know how to run it, though that is …
=> Replace non-XML 1.0 characters with space

app/models/article.rb, app/views/article/_article_links.html.slim
Address #2010 by refactoring queries that look for article links.  Note that this may cause bugs in the listing of pages that mention an article.
=> Article links query refactored for #2010

app/controllers/transcribe_controller.rb
This pares the `still_editing` action down to 3 SQL calls.  
Previously this action called 17 SQL statements.
=> Resolves #2026 by paring still_editing down to the minimum

app/controllers/iiif_controller.rb, app/models/document_set.rb, app/views/devise/sessions/new.html.slim, config/routes.rb
Closes #2101 by
* Exposing a new API endpoint to list a user's collections
* Adding support for user-based queries into the collections API, which makes that API functional for projects that were not imported via IIIF or are CONTENTdm-based.
* Adding support for document sets to the API
* Improving performance of most API calls.
=> 2101 enhance iiif api

app/controllers/document_sets_controller.rb, app/models/document_set.rb, app/views/document_sets/index.html.slim, config/locales/document_sets/document_sets-en.yml
This adds a work search bar to the collection-level document set assignment screen and has the set-specific assignment screen's search bar duplicate the metadata search present elsewhere.
Closes #2119
=> 2119 work search doc set

app/controllers/sc_collections_controller.rb, app/helpers/application_helper.rb, app/models/sc_manifest.rb, app/views/sc_collections/explore_collection.html.slim, app/views/sc_collections/explore_manifest.html.slim, lib/tasks/iiif_collection_import.rake
Closes #2122
This modifies the following
* When importing from CONTENTdm or IIIF, a the target collection select list is sorted by collection title and now displays document sets under each collection
* If a document set is chosen, imported works are added to the target collection and also the target document set.
=> 2122 assign sets on import

app/assets/stylesheets/base/global.scss, app/helpers/abstract_xml_helper.rb, app/helpers/export_helper.rb, app/models/page.rb, app/views/transcribe/display_page.html.slim, lib/search_translator.rb
Resolves #2223 
To test, mark up an abbreviation with an `orig` attribute and one without an `orig` attribute, then check all display and export formats.
=> 2223 expan tag

app/controllers/deed_controller.rb, app/views/admin/index.html.slim, app/views/deed/_deed.html.slim, config/routes.rb
Resolves #2246 and does the following:
Adds a site-wide notes stream of notes on public collections, links to it from the admin dashboard, improves performance of deed rendering for the activity stream for collections and the site, and changes the activity stream page link from transcribe to overview for a page.
=> Show all notes for #2246, improved perf, link to display

app/models/collection.rb
Change default transcription conventions away from Julia Brumfield Diaries conventions.  (This addresses but might not fix #2059)
=> Improve default transcription conventions for #2059

lib/contentdm_translator.rb
Resolves #2407.  To remediate previous imports, we should run `rake fromthepage:cdm_work_update[sc_manifest_id,true] --trace` for any imported OCR correction projects about which customers have complained.
=> 2407 handle new cdm uris

app/controllers/concerns/export_service.rb
This adds columns in the export for cells which have been renamed.
=> Handle renamed column headings on export for @2490

app/views/transcription_field/_field_layout.html.slim
Re #2501 - This is how I've changed the condition to show `.fields-row` (based on your suggestion in Slack)
```ruby
-page_number = array.map{|field| field.page_number}.uniq.first
-if (@page && (page_number == @page.position || page_number == nil)) || (current_page?({action: 'edit_fields'}))
```
=> Fix empty space in multi-page field layout

app/controllers/transcribe_controller.rb, app/views/shared/_handsontable.html.erb
This adds logging for field-based transcriptions, which have not had our fail-safe logging in the past.
It also fixes a nested loop performance problem.
=> Add logging for #2555 and improve rendering performance

app/controllers/display_controller.rb
Handle spaces in search strings, so that a search for `morgan s` becomes a search for `"morgan s"` instead of a search for `morgan AND s`.
=> Improve text search performance/functionality for #2360

app/helpers/abstract_xml_helper.rb
Handle hyphens at the beginnings of paragraphs and `figure` tags with no `rend` attribute.
To test, verify #2556 and do a full HTML export from a copy of Mount Auburn's collection.
=> Handle odd formatting for #2556

app/views/transcription_field/edit_fields.html.slim
Re #2606 - Interesting bug, took some time to figure it out :)
Reordering was working correct, so if you _refresh the page_ after reordering everything will be fine. But reordering didn't update the line number value in the hidden input, so if you _submit the form_ right after reordering, it will post the wrong (old) line numbers and update. The small fix should resolve the issue.
=> Preserve new fields order after save

app/models/page.rb
Closes #2494 
To test:
* Do a plaintext export of a markdown-encoded work (JWG or Mount Auburn)
* Do a plaintext export of a spreadsheet-entered work
=> Format tables in plaintext export for #2494

app/helpers/transcribe_helper.rb
To test:
* View a IIIF-imported page
* View an Internet Archive-imported page
* View a large uploaded page
=> Use riiif to serve OSD images to Safari/iOS for #2626

app/assets/stylesheets/sections/page.scss
Re #2622 - set minimum height of the transcription column to half of the available viewport height in vertical layout mode.
=> Fix editor min height

app/controllers/bulk_export_controller.rb, app/controllers/concerns/export_service.rb, app/controllers/dashboard_controller.rb, app/controllers/export_controller.rb, app/helpers/export_helper.rb, app/models/bulk_export.rb, app/views/bulk_export/index.html.slim, app/views/bulk_export/new.html.slim, app/views/dashboard/_owner_header.html.slim, app/views/dashboard/exports.html.slim, app/views/export/facing_edition.html.erb, app/views/shared/_work_tabs.html.slim, app/views/user_mailer/bulk_export_finished.html.erb, app/views/work/download.html.slim, config/routes.rb, db/migrate/20210615223422_add_work_id_to_bulk_export.rb, db/migrate/20210623214318_add_facing_pdf_to_bulk_export.rb, db/schema.rb, lib/tasks/bulk_export.rake
This PR attempts the following:
* Provide an easier way for project owners to launch exports (issue #2395)
* Improve the usability for bulk exports (issue #2426)
* Make work-specific field/table CSV exports run in the background (TNA)
* Fix problems with email clients that won't download zip files (issue #2551)
* Deliver the facing edition export feature by backgrounding it (issue #2436)
To test:
* The download tab should be available to project owners regardless of whether the feature flag is enabled
* If the feature flag is enabled and the collection allows, it, non-owners should see the download tab but not see the new zip export flags
* The bulk export UI should be more usable; launching a bulk export should send the user to a new "exports" tab.
* Work-specific bulk exports launched …
=> 2395 bulk export work download

app/views/shared/_osd_div.html.slim
To be honest, I wasn't sure it is possible so it took some time to research, but I think the final result is fine.
This is how it works:
1. When user press a mouse button (or touch started) in the OSD area it tries to find any focused element inside the edit area. It could be an input, text area, CodeMirror editor, spreadsheet cell.
2. If a focused element found, it will store in a variable until the mouse button (or touch) released.
3. Once released (means, user finished interaction with OSD), it will restore the focus to the element. It will even restore the caret position and text selection (if something was selected).
This should work fine for image panning, accidental clicks on image area, and OSD toolbar buttons like zoom in, zoom out (except our custom filters button)
=> Preserve edit area focus

app/models/work.rb
When we delete a work that has had work-level bulk exports, we need to delete the (child) bulk export records as well.
=> Fixes #2676 by deleting work-level exports when deleting a work

app/models/collection_statistic.rb, app/models/document_set_statistic.rb, app/models/page.rb, app/models/work_statistic.rb, app/views/statistics/_collection_statistics.html.slim, config/locales/statistics/statistics-en.yml, db/migrate/20211103155043_add_line_count_to_pages.rb, db/schema.rb, lib/tasks/update_line_counts.rake
Note that we will need to run `rake fromthepage:update_line_counts[100,105]` in batches for each of the 2000+ collections, ideally in reverse order.
=> 2875 lines or records stats

app/controllers/bulk_export_controller.rb, app/controllers/export_controller.rb, app/models/bulk_export.rb, app/models/document_set.rb, app/views/dashboard/exports.html.slim, app/views/export/index.html.slim, app/views/shared/_collection_tabs.html.slim, app/views/user_mailer/bulk_export_finished.html.erb, db/migrate/20211102194016_add_document_set_to_bulk_export.rb, db/schema.rb
This adds the export tab to document sets.  It does not implement set-specific coocurrence or CONTENTdm exports, but should support everything else.
=> Export document sets for #2504

app/views/statistics/_collection_statistics.html.slim
To duplicate the issue locally, navigate to a document set, save a page, then view the set statistics.
=> Fix #2912 by removing question mark

app/controllers/concerns/export_service.rb
This seemed to have come from exporting a spreadsheet that had been transcribed with 8 header fields, 4 of which had since been deleted.
=> Fixed #2927 by testing for deleted configs

app/views/page/edit.html.slim
Hide page image replacement options if no image was uploaded.
=> Fixed #2892 by hiding image replacement for imports

app/views/export/facing_edition.html.erb
This fixes the problem with apostrophes in metadata.  It does not address the (observed) back-slash in front of square braces.
=> Fix apostrophe in PDF metadata block for #2899

app/views/transcription_field/_field_layout.html.slim, app/views/transcription_field/_metadata_field_layout.html.slim
Fixes #2961 
To reproduce:
In a field-based project, add an Instruction field with HTML tags.
Verify that the preview renders the HTML instead of escaping the tags.
Repeat in a metadata project.  (Separate code paths; sigh.)
=> Don't escape HTML in instruction fields #2961

app/views/work/download.html.slim
Currently, analyzing a work via the Download page opens links on the same page, which is not what we want. 
This uses `target: :_blank` to open the links on a new page instead.
=> changed the export links to open in a new tab for #2960

app/views/dashboard/owner.html.slim, spec/features/collection_spec.rb, spec/features/owner_actions_spec.rb, spec/features/zz_deletion_spec.rb
_Resolves #2953_ 
Originally, the links to specific works on the [owner dashboard](https://fromthepage.com/dashboard/owner) would link to the work's settings page instead of the work's "read" page, which is not the expected behavior.
These are the work links, and in the bottom left corner you can see it's taking you to the "edit" page.
This pull changes the links to open the "read" page instead.
=> change owner dashboard work links to open read tab for #2953

config/locales/transcribe/transcribe-en.yml
_Resolves #2871_
Currently, the "preview", "edit", and "autolink" buttons on the transcription page are missing their translations. Their tooltips are missing translations as well. This is true for English, Spanish, and Portuguese. 
This is what the "preview" button currently look like on hover, and the other two look smiliar.
This pull adds the six English translations for these buttons.
The Spanish and Portuguese translations still need to be added as well.
=> add english translations to the preview, edit, and autolink buttons and their tooltips for #2871

app/controllers/collection_controller.rb, app/models/collection.rb, app/views/collection/edit.html.slim, config/locales/collection/collection.en.yml, spec/features/disable_subjects_spec.rb
_Resolves #2872_
Previously, the "subject linking" / "subject indexing" toggle in the Collection settings page had a double negative, which is counterintuitive and confusing.
Changing the wording to "Enable subject linking" and flipping the boolean going to the database solves this.
Previously, the `check_box`es were using a `value` parameter to set their state. However, we found this parameter is not doing anything as `check_box`es [use the `method` passed to them to set their state](https://www.rubydoc.info/docs/rails/4.1.7/ActionView%2FHelpers%2FFormBuilder:check_box). So, all uses of the `value` parameter in the `collection/edit` view were removed.
=> changed disable subject linking to enable for #2872

app/views/dashboard/landing_page.html.slim
_Resolves #2393_
Previously, HTML entities like ampersands in collection descriptions in the Find a Project page were incorrectly escaped (i.e `&amp;` is shown instead of `&`). 
However, the ampersands show up as expected (`&`) on the Collection overview page and owner dashboard. The difference is that on the Find a Project page, `strip_tags` is called on the description, which [is escaping special characters](https://github.com/rails/rails/issues/28060).
To change this behavior, we use `Loofah.fragment(desc).text(encode_special_chars: false)` instead of `strip_tags(desc)`, which does the same thing (removes HTML tags) without escaping special characters ([here's the documentation](https://www.rubydoc.info/github/flavorjones/loofah/Loofah/TextBehavior)). 
`strip_tags` is in three places …
=> Change how tags are stripped for #2939

app/controllers/collection_controller.rb
_Resolves #2956_
Right now, collaborator and owner lists on the collection settings page are listed in the order that they were added, which is unhelpful in finding specific users to remove them. 
These lists are now sorted alphabetically by the users' display name.
=> Sorted owners, collaborators, and reviewers alphabetically for #2956

app/helpers/transcribe_helper.rb, app/models/sc_canvas.rb
Quartex's canvases have images with service `@id`s that end with a slash, causing our attempts to append other URL elements to break.  This eliminates terminal slashes before appending a new slash for page thumbnails and OSD tiles.
=> Handle @id values ending with slash for #3066

app/controllers/collection_controller.rb, app/controllers/document_sets_controller.rb, app/controllers/work_controller.rb, app/models/collection.rb, app/models/document_set.rb, app/models/work.rb, app/views/document_sets/settings.html.slim, config/locales/en.yml
_Resolves #2328_
Previously, the input for slugs/URLs for collections and works had no validation and could be set as just numbers, which causes problems.
Now, when a user tries to save an invalid slug (that has no letters in it, via the regex expression `/[[:alpha:]]/`), an error message will show and the slug will not save.
On the collection page:
On the work page:
There's also a couple of changes related to #2995 (subject linking enabled) that were necessary to get this working.
=> Added collection, work, and document set slug validation for #2328

app/views/transcription_field/_metadata_field_layout.html.slim
Previously, we were displaying the Wrangel Island select lists in the metadata form, but when the user chose them and saved the page, the values looked like they were not selected.
In fact, the values in the configuration screen hand been entered in a multi-line mode (which might be the way we do all options for metadata entry, not just the multi-select we designed it for), so the value for e.g. `Roald Amundsen` was `\nRoald Amundsen`.  This would be saved (probably without the whitespace), but when the form was re-loaded the whitespace mismatch meant the select box couldn't find the appropriate option.
=> Remove whitespace to fix #3046

app/models/work.rb
LVA has work titles with underscores or dashes, which were not allowed with the alpha regex matching.  Since they upload large zip files, we would get 80% of the way through, run into one of these, and then fail for the entire upload.
=> accept any work slug with alphabet characters or a dash or underscore

app/views/shared/_collection_tabs.html.slim
_Resolves #3129_
If there are no pages to review in a collection, the "review" tab will not show up at all.
=> Hide review tab if no pages need review for #3129

app/views/collection/edit.html.slim, app/views/work/edit.html.slim, config/locales/collection/collection.en.yml, config/locales/work/work-en.yml
_Resolves #3130_
On the collection settings page, the collection's URL is displayed as well as a URL to send to transcribers. On the work settings page, the work's URL is displayed as well.
These URLs look like `www.fromthepage.com/user/collection` but we want them to:
1. Include the HTTP/HTTPS protocol being used
2. Reflect the user's environment, like `fromthepage.com` or `localhost`
So, now on my AWS environment the URLs look like:
On a FTP.com environment, it would look like:
=> Changed current collection/work link to include protocol and env for #3130

app/models/work.rb, app/views/work/edit.html.slim
_Resolves #2976_
Currently, the "Document Date" field under "Additional Metadata" in work settings is required to be in ETDF format and a validation error pops up if it's not:
> 1 error prohibited the form from being saved:
> Document date must be in EDTF format
This works, but isn't very intuitive because some users (such as Molly of History Revealed, who emailed about this issue) don't know what EDTF format is or don't understand what the validation error means.
A better way to restrict dates to EDTF format is to use an input mask (to `yyyy-mm-dd`), this pull adds that.
Though this works perfectly with dates at one specific day, there are more possible date types. [EDTF allows](https://www.loc.gov/standards/datetime/):
- year, month, and day (e.g. 2016-05-10) _(what this allows)_
- year …
=> Make EDTF date input more intuitive for #2976

app/assets/stylesheets/sections/work.scss, app/views/work/edit.html.slim, config/locales/work/work-en.yml
_Resolves #2952_
If a work is restricted, its collection is private, and there are no collaborators added, only project owners will be able to edit the work. There are some works that meet all these requirements but are probably unaware of this.
This adds a warning message if a work is restricted, its collection is private, and there are no collaborators added. It looks like this:
=> Added warning message if work restricted with no collaborators for #2952

app/views/work/edit.html.slim, config/locales/work/work-en.yml
_Resolves #2976, related to #3115_
This adds a hint for the Document Date input in a work's additional metadata that the date should be in EDTF format.
We'd previously discussed either adding this hint or adding (EDTF) after the "Document Date" label; I think the hint is more helpful.
=> Added EDTF hint for document dates for #2976

app/controllers/export_controller.rb, app/models/collection.rb, app/models/document_set.rb, app/views/article/show.html.slim, config/routes.rb, lib/subject_distribution_exporter.rb
Subject distribution export is different from subject coocurrence export these ways:
- Limited to a single subject, listing subjects that occur in the same work as that subject
- Lists coocurrences even if they do not appear on the same page, but are on another page in the work
- Aggregated by subject _and work_
=> New subject distribution URL and export for #2628

app/controllers/article_controller.rb, app/views/article/show.html.slim, config/routes.rb
_Resolves #3166_
This removes the options to change the subject graph on a subject page [like this one](https://fromthepage.com/benwbrum/jeremiah-white-graves-diaries/article/66587) because they don't pass accessibility testing & we don't know how to fix it.
It also removes all related code in the controller and routing.
=> Removed options for changing subject graph for #3166

app/controllers/article_controller.rb, app/views/article/list.html.slim
_Resolves #2385_
> On the subjects pages, subject terms would be easier to read and identify if they were organized alphabetically vertically in the column, rather than horizontally.
This is how the subject list was previously displayed, with subjects alphabetically going across and then down.
The subjects are now listed alphabetically going down and then across.
Because the subjects are showed in 3 columns using `float: left`, they are inherently sorted horizontally and cannot easily be organized vertically (there is no `float: down`). So, to organize them vertically, I could either: (1) change how the subject list is displayed, or (2) place the subjects into the list in an order in which they would be organized vertically. Because I didn't quickly find a way to implement the first, I …
=> Made subject list organized vertically instead of horizontally for #2385

Gemfile, Gemfile.lock, config/application.rb, config/i18n-tasks.yml, config/locales/article_version/article_version-fr.yml, config/locales/en.yml, config/locales/es.yml, config/locales/pt.yml
_For #3165_ 
Before translating all of our locales to French, we should test the translation on one small group. I used `article_version` for this as it only has 9 keys and around 600 characters.
=> Test translation to French

app/models/deed_type.rb, app/views/admin/expunge_confirmation.html.slim, app/views/admin/visit_deeds.html.slim, app/views/deed/list.html.slim, app/views/user/profile.html.slim, config/locales/deed/deed-en.yml, config/locales/deed/deed-fr.yml
_For #3232, deed type buttons not translated_
Previously, the deed types shown on the deed list (above) weren't translated to non-English locales because they were explicitly written in to the `DeedType` model:
https://github.com/benwbrum/fromthepage/blob/4fe18a3b14ceace5458e394db8151f3b3ef87b32/app/models/deed_type.rb#L30-L35
In this PR I changed the `TYPES` hash to map to calls to `I18n.t` instead of plaintext.
This works to translate the deed list (above), but I'm not sure if it will break anything else?
=> Changed deed type hash to be translatable

config/locales/activerecord/activerecord-pt.yml, config/locales/article/article-pt.yml, config/locales/article_version/article_version-pt.yml, config/locales/bulk_export/bulk_export-pt.yml, config/locales/category/category-pt.yml, config/locales/collection/collection-pt.yml, config/locales/contact/contact-pt.yml, config/locales/dashboard/dashboard-pt.yml, config/locales/deed/deed-pt.yml, config/locales/devise/devise-pt.yml, config/locales/display/display-pt.yml, config/locales/document_sets/document_sets-pt.yml, config/locales/export/export-pt.yml, config/locales/ia/ia-pt.yml, config/locales/layouts/application-pt.yml, config/locales/metadata/metadata-pt.yml, config/locales/notes/notes-pt.yml, config/locales/page/page-pt.yml, config/locales/page_version/page_version-pt.yml, config/locales/pt.yml, config/locales/quality_samplings/quality_samplings-pt.yml, config/locales/sc_collections/sc_collections-pt.yml, config/locales/shared/shared-pt.yml, config/locales/statistics/statistics-pt.yml, config/locales/transcribe/transcribe-pt.yml, config/locales/transcription_field/transcription_field-pt.yml, config/locales/user/user-pt.yml, config/locales/user_mailer/user_mailer-pt.yml, config/locales/will_paginate/will_paginate-pt.yml, config/locales/work/work-pt.yml
_Resolves #3180_
This translates all of the remaining untranslated Portuguese messages so that you shouldn't see any leftover English when you have your locale set to Portuguese. It was done via `i18n-tasks translate missing` and the Google Translate API.
This PR we can merge now because robot Portuguese is better than English (and so our `i18n-tasks` tests can run), and we'll have a separate PR (#3255) for reviewing these messages.
=> Added missing Portuguese messages

config/locales/activerecord/activerecord-es.yml, config/locales/article/article-es.yml, config/locales/article_version/article_version-es.yml, config/locales/bulk_export/bulk_export-es.yml, config/locales/category/category-es.yml, config/locales/collection/collection-es.yml, config/locales/contact/contact-es.yml, config/locales/dashboard/dashboard-es.yml, config/locales/deed/deed-es.yml, config/locales/devise/devise-es.yml, config/locales/display/display-es.yml, config/locales/document_sets/document_sets-es.yml, config/locales/es.yml, config/locales/export/export-es.yml, config/locales/ia/ia-es.yml, config/locales/layouts/application-es.yml, config/locales/metadata/metadata-es.yml, config/locales/notes/notes-es.yml, config/locales/page/page-es.yml, config/locales/page_version/page_version-es.yml, config/locales/quality_samplings/quality_samplings-es.yml, config/locales/sc_collections/sc_collections-es.yml, config/locales/shared/shared-es.yml, config/locales/statistics/statistics-es.yml, config/locales/transcribe/transcribe-es.yml, config/locales/transcription_field/transcription_field-es.yml, config/locales/user/user-es.yml, config/locales/user_mailer/user_mailer-es.yml, config/locales/will_paginate/will_paginate-es.yml, config/locales/work/work-es.yml
_Resolves #3179_
This translates all of the remaining untranslated Spanish messages so that you shouldn't see any leftover English when you have your locale set to Spanish. It was done via `i18n-tasks translate missing` and the Google Translate API.
This PR we can merge now because robot Spanish is better than English (and so our `i18n-tasks` tests can run), and we'll have a separate PR (#3253) for reviewing these messages.
=> Added missing Spanish messages

config/locales/deed/deed-en.yml, config/locales/devise/devise-en.yml, config/locales/work/work-en.yml, spec/features/deed_list_spec.rb, spec/features/display_marked_as_blank_spec.rb
_Resolves #3242_
-  Changed "Display name" to "Organization name"
-  Changed "Support translation" to "Enable translation"
-  Removed "page", "work", "collection" in deeds (i.e. "Sylvie transcribed page Image 1 in the work Diary of Matilda Brown in Test Collection collection)
=> Updated English wording

app/views/collection/show.html.slim, config/locales/collection/collection-en.yml, config/locales/collection/collection-es.yml, config/locales/collection/collection-fr.yml, config/locales/collection/collection-pt.yml
_Resolves #3265_
User "wrote" note previously was in plaintext in the collection `show` view. This PR extracts it to locales and adds translations in all 4 languages.
=> Extracted & localized "wrote" in recent notes

app/controllers/deed_controller.rb, app/views/deed/_deeds.html.slim, app/views/deed/list.html.slim, config/locales/deed/deed-en.yml, config/locales/deed/deed-es.yml, config/locales/deed/deed-fr.yml, config/locales/deed/deed-pt.yml
_Resolves #3261_
Previously, the "show more" (deed list) page for a collection owner was showing _all_ of the FTP deeds instead of just deeds related to that owner.
This is because only `options[:user_id]` was being passed to the deed list page, which was `nil`, as `options[:owner]` is what carried the owner's id. Now `options[:owner]` is passed if `options[:user_id]` is `nil`. 
In the deed list, it's checked if `@user` is an owner or not, and if it is, the deeds to display will be deeds on that owner's collections, just like on the shortened deed list.
=> Made owner deed list show owner's collection's deeds

app/models/document_set_statistic.rb
_Resolves #3269_
Document set statistics were showing the `{one:, other:}` from the locale because the `count` being passed in to `t()` was `nil`. The count was `nil` because the `:pages_transcribed`, `:pages_incomplete`, `:pages_needing_review`, and `:descriptions` statistics weren't being set in the `document_set_statistic` `get_stats_hash` method.
This PR adds those statistics to document sets, and now the statistics look fine:
=> Added missing document set statistics for #3269

app/helpers/application_helper.rb, app/models/deed.rb, app/views/deed/_deed.html.slim, app/views/deed/_deeds.html.slim, db/migrate/20220812203801_change_deeds_prerender_size.rb, db/schema.rb
_Resolves #3262_
Deeds for short-form lists (i.e. on a collection's page, an owner dashboard, etc.) are pre-rendered and were previously stored as a string of HTML, in the locale of the user who created them. 
This changes the deeds' prerender to store the string of HTML in _each_ locale. When the deed is displayed, it's displayed in the _current_ user's locale.
When the deed's prerender is stored, a hash is created that maps each locale (excluding regional locales, to save space as they aren't currently any different for deeds) to the string of HTML in that locale. The deed is rendered in different locales by putting the `_deed` partial in a `I18n.with_locale` block. The hash is then converted to JSON to be stored in the db as a string.
A migration was made to increase the size of …
=> Localized prerendered deeds

app/helpers/dashboard_helper.rb, app/views/dashboard/landing_page.html.slim
_Resolves #3146_
This uses Nokogiri to remove the `style` element and its contents from collections' `intro_block`s when they're being shown as a snippet on the Find a Project page, because previously the contents of the `style` element were showing up instead of the collection's description.
With this PR, there is no HTML in the snippet _and_ ampersands show up correctly.
We were initially using `strip_tags` to remove HTML tags from the collection's description and shorten it for the Find a Project page. `strip_tags` automatically removed the `style` element and its contents, so there was no HTML shown like there is in this issue. However, `strip_tags` escaped special characters like `&` to `&amp;`, which we did not want.
So [we switched …
=> Strip style elements from snippets for #3146

config/locales/collection/collection-fr.yml
_Resolves #3271_
This changes the French translation of "needs work" from "besoin de œuvre" to "besoin d'amélioration"
This was the only one place I could find that says "...need(s) work"
=> Fixed French "needs work" translation for #3271

app/controllers/application_controller.rb, app/views/layouts/application.html.slim, app/views/user/update_profile.html.slim, config/application.rb, config/locales/en-GB.yml, config/locales/en.yml, config/locales/fr-CA.yml
_For #3249_
This adds 2 regional locales (`en-GB` and `fr-CA`) to see if regional locales work as expected. 
In `en-GB`, I replaced all messages that include "color" to use "colour"; in `fr-CA`, I replaced all messages that include "OCR" to use "ROC".
As hoped, you only have to include the messages you want to override from the base language. `en-GB.yml` only includes messages with "colour", and `fr-CA.yml` only includes messages with "ROC". 
If you have your browser's language set to English (UK), your locale will be `en-GB`; the same goes for `fr-CA`. You can also pick a regional locale from the locale switcher dropdown.
1. Do we want to keep the regional locales on the locale switcher? If so, how do we want to display them there?
2. Are there any other regional locales we want to add? …
=> Proof of concept for regional locales

app/controllers/collection_controller.rb, app/controllers/display_controller.rb, app/views/collection/needs_review_pages.html.slim, app/views/display/_pages_view.html.slim, config/locales/collection/collection-en.yml, config/locales/collection/collection-es.yml, config/locales/collection/collection-fr.yml, config/locales/collection/collection-pt.yml, config/locales/display/display-en.yml, config/locales/display/display-es.yml, config/locales/display/display-fr.yml, config/locales/display/display-pt.yml
_Resolves #3258_
Anywhere that pages were being listed (for needing indexing, review, transcription, all pages, etc.) had the heading "Pages that need transcription", but that's not actually what was being shown.
This was because the `_pages_view` partial that all of these use had the heading statically set to "Pages that need transcription".
I changed the heading to display a `@heading` variable which each controller can set depending on what type of pages will be shown.
=> Made pages_view heading changeable for #3258

config/locales/category/category-en.yml
_Resolves #3277_
This removes the "t" from "Save changest"
=> Fixed typo on category's "save changes" for #3277

app/views/collection/_contributors_body.html.slim, config/locales/collection/collection-en.yml, config/locales/collection/collection-es.yml, config/locales/collection/collection-fr.yml, config/locales/collection/collection-pt.yml
_Resolves #3273_
This changes the "Active collaborators" section of the collection collaborators page to have a table with collaborator's time instead of the times in parentheses.
It also changes the "Export as CSV" button to say "Export detailed activity as CSV"
I'm pretty sure this is the only page that has this section.
=> Changed transcriber actvity time to a table for #3273

app/controllers/collection_controller.rb, app/views/collection/works_to_review.html.slim
_Resolves #3279_
This paginates the `/works_to_review` page to resolve its performance issue when it includes a lot of works.
Here's how the page looks now:
This makes the page load only 15 works at a time, reducing the page's load time from 9 minutes (LVA - 13,000 works) or 50 seconds (1,700 works) to around or less than a second.
=> Paginated works_to_review page for #3279

app/models/owner_statistic.rb, app/views/statistics/_collaborator_time.slim, app/views/statistics/_statistics.html.slim, config/locales/statistics/statistics-en.yml, config/locales/statistics/statistics-es.yml, config/locales/statistics/statistics-fr.yml, config/locales/statistics/statistics-pt.yml, spec/features/owner_view_spec.rb
_Resolves #3245_
Here's a draft of improving the owner dashboard summary statistics.
- I moved the date range input from the `collaborator_time` partial to the `statistics` one. 
- The second group of statistics now shows the statistics in the given date range instead of the last 7 days.
- Heading changed from "Last 7 days statistics" to "Statistics from date to date" 
- I updated the statistic methods in `owner_statistic.rb` to take date ranges (by changing `last_days_clause` to `date_range_clause`). An input of `7` for "the last 7 days" still works.
I didn't include the "Active collaborators" or "All collaborator emails" sections from the collection collaborators page, but I can add that if it's wanted.
=> First attempt at improving owner dashboard summary for #3245

app/controllers/collection_controller.rb, app/views/collection/reviewer_dashboard.html.slim
_Helps #3281 (not sure if it fixes it)_ 
There are 6 statistics on the `/review` page, but only 4 are shown if you aren't an owner of the collection (or a reviewer if the collection has a restricted review type). However, all 6 of the statistics are still loaded. This is problematic because with a lot of works, some of the db queries for these statistics take a long time (the one off page count, one that's not shown, takes up to 7-15 seconds for the LVA WWI collection!). 
This PR moves these queries to the view so that they're only executed if they're needed, which should improve the performance of the page if you're not an owner or authorized reviewer of the collection.
=> Moved db queries to view to only load them if needed for #3281

app/views/collection/edit.html.slim, app/views/collection/new.html.slim, app/views/dashboard/_empty.html.slim, app/views/document_sets/_edit.html.slim, app/views/document_sets/new.html.slim, app/views/work/edit.html.slim, app/views/work/new.html.slim, config/locales/collection/collection-en.yml, config/locales/collection/collection-es.yml, config/locales/collection/collection-fr.yml, config/locales/collection/collection-pt.yml, config/locales/dashboard/dashboard-en.yml, config/locales/dashboard/dashboard-es.yml, config/locales/dashboard/dashboard-fr.yml, config/locales/dashboard/dashboard-pt.yml, config/locales/document_sets/document_sets-en.yml, config/locales/document_sets/document_sets-es.yml, config/locales/document_sets/document_sets-fr.yml, config/locales/document_sets/document_sets-pt.yml, config/locales/work/work-en.yml, config/locales/work/work-es.yml, config/locales/work/work-fr.yml, config/locales/work/work-pt.yml
_Resolves #3267_
This adds help text for collection, document sets, and works for description and transcription convention input.
Here's how the help text looks in a few places:
=> Added help text for descriptions and transcription conventions for #3267

app/controllers/application_controller.rb
This time I think I've found the problem: `locale` is a symbol occasionally, which makes it blow up on the call to string `include?`.  Since `locale` is set in a series of fall-backs, I'm not sure how it became a symbol, but I think this may fix the problem.
=> Address #3293 by casting to string implicitly

config/i18n-tasks.yml, spec/i18n_spec.rb
_Resolves #3430_
This fixes the falsely reported missing and unused translations by adding them to `ignore_missing` and `ignore_unused` of `config/i18n-tasks.yml`.
The "unused" translations were reported because they're used dynamically:
https://github.com/benwbrum/fromthepage/blob/66c67e78f30ec7960428743743a2a635f18ac3f1/app/views/collection/edit_buttons.html.slim#L11-L12
The "missing" translations were reported because the translations aren't in our locale files, but they're not actually missing on the site.
=> Ignore false missing & unsued translations for #3430

Gemfile, Gemfile.lock
_Resolves #3432_
This changes our Gemfile to use the base `i18n-tasks` gem instead of my fork of it so the gem can continue getting future updates.
=> Don't use fork of i18n-tasks anymore for #3432

app/views/collection/show.html.slim, config/locales/collection/collection-en.yml, config/locales/collection/collection-es.yml, config/locales/collection/collection-fr.yml, config/locales/collection/collection-pt.yml
_Resolves #1043_
Previously, the "help out!" link on the collection show page was shown to all users, even if the work was restricted and the user wasn't a collaborator. This PR makes the "help out!" link only show if the user `can_transcribe?` the work (if the work isn't restricted, if they're an owner of the work, or if they're a collaborator on the work). Otherwise, it'll say that "Collaboration is restricted" and won't have a link to transcribe.
Here's how it looks, the work on the top is restricted and the work on the bottom is not.
=> Only show "help out" link to work collaborators for #1043

app/assets/javascripts/landing.js, app/views/shared/_landingheader.html.erb, app/views/static/digital_scholarship.html.erb, app/views/static/public_libraries.html.erb, app/views/static/state_archives.html.erb, app/views/static/transcription_archives.html.erb
_Resolves #3427_
This changes all of the `<img src="/assets/...">` tags into `<%= image_tag("...") %>`s so that these landing pages will work in production.
=> Use image helpers for image tags in landing pages for #3427

app/views/transcribe/_save_buttons.html.slim, config/locales/transcribe/transcribe-en.yml, config/locales/transcribe/transcribe-es.yml, config/locales/transcribe/transcribe-fr.yml, config/locales/transcribe/transcribe-pt.yml
_Resolves #3365_
Previously, people could double-click the page save buttons and this could cause duplicate subjects to be created. To fix this, this PR disables the "save" or "done" or "approve" buttons after the form has been submitted. It does this via the `data-disable-with` attribute.
Here's a video of how it looks:
https://user-images.githubusercontent.com/35716893/207950887-3f06cd15-dbe6-4109-a397-7765e06a7be9.mp4
Are there any other save buttons we want to add this to?
=> Made transcribe save buttons disable after click for #3365

app/helpers/export_helper.rb, app/views/export/tei.html.erb
This resolves #3442 by escaping strings used in the XML export.
It resolves #3443 by handling empty strings in users's `real_name` fields.
It also adds a `type="psedonym"` attribute to the exported `persName` of a user if they have a blank `real_name`.
=> Handle unusual data for #3442 and #3443

app/controllers/dashboard_controller.rb, app/models/owner_statistic.rb, app/views/statistics/_collaborator_time.slim
_Resolves #3317_
Previously, the owner dashboard summary tab "Collaborator Time" section was somewhat inaccurate as it was pulling from the `AhoyActivitySummary`:
https://github.com/benwbrum/fromthepage/blob/fa6b500e4aae850bc7918df4aa2fa53696ba7a83/app/controllers/dashboard_controller.rb#L109-L113
instead of from deeds, like the "Collaborators" tab of a collection does, which is more accurate.
This PR refactors the owner summary collaborator section to work the same way that the collection collaborators tab does. The new code for this was put into the `owner_statistic.rb` model. The code is based on part of the [`new_contributors` method of `contributor_helper.rb`](https://github.com/benwbrum/fromthepage/blob/development/app/helpers/contributor_helper.rb#L29-L60), which gets the …
=> Refactor owner summary contributors to use deeds for #3317

app/views/user_mailer/upload_finished.html.erb, app/views/user_mailer/upload_finished.text.erb, config/locales/user_mailer/user_mailer-en.yml, config/locales/user_mailer/user_mailer-es.yml, config/locales/user_mailer/user_mailer-fr.yml, config/locales/user_mailer/user_mailer-pt.yml
_Resolves #2981_
This adds the name of the file uploaded to the upload notification email. If a .zip file was uploaded, the name of the zip file will be shown, not the included filenames.
Susan Gray at LVA wanted a list of files uploaded in the upload notification email, but it doesn't seem like the files in the .zip file are recorded in the `DocumentUpload` object. If we think the list is important, I can investigate further how to find it.
=> Added filename in upload finished email for #2981

app/controllers/collection_controller.rb, app/helpers/contributor_helper.rb, app/views/collection/_contributors_body.html.slim, config/locales/collection/collection-en.yml, config/locales/collection/collection-es.yml, config/locales/collection/collection-fr.yml, config/locales/collection/collection-pt.yml
This implements the use of AhoyActivitySummary for the collection-level collaborators tab.
It also fixes a bug I noticed in which viewing the contributors for a single week 2 years ago shows as "New Transcribers" every single person who was new since the beginning of the span, not just the transcribers during the single week.
It also fixes a bug I noticed in which we were only showing new transcribers for "transcription" deeds, ignoring edits and OCR corrections.
=> Resolves #3496 for collections and fixes new collaborators

app/controllers/display_controller.rb, lib/tasks/ingestor.rake
=> Enhanced sorting for numeric and alphanumeric titles

app/helpers/abstract_xml_helper.rb, app/models/editor_button.rb, app/views/shared/_codemirror.html.erb, config/locales/collection/collection-de.yml, config/locales/collection/collection-en.yml, config/locales/collection/collection-es.yml, config/locales/collection/collection-fr.yml, config/locales/collection/collection-pt.yml
_Resolves #3461_
This adds an italics tag to the advanced editor.
Here is how it looks in the editor buttons settings:
Here is how it looks in the editor:
And the result:
=> Added italics tag for #3461

app/helpers/abstract_xml_helper.rb
Closes #3699 
To test, add an HR element to a page transcript, then try to export it.
=> Fixes #3699 by balancing empty HR elements

app/assets/stylesheets/sections/dashboard.scss, app/controllers/dashboard_controller.rb, app/helpers/collection_helper.rb, app/helpers/dashboard_helper.rb, app/models/collection_statistic.rb, app/views/collection/show.html.slim, app/views/dashboard/owner.html.slim, app/views/shared/_progress.html.slim, config/locales/collection/collection-de.yml, config/locales/collection/collection-en.yml, config/locales/collection/collection-es.yml, config/locales/collection/collection-fr.yml, config/locales/collection/collection-pt.yml, config/locales/dashboard/dashboard-de.yml, config/locales/dashboard/dashboard-en.yml, config/locales/dashboard/dashboard-es.yml, config/locales/dashboard/dashboard-fr.yml, config/locales/dashboard/dashboard-pt.yml, spec/features/add_data_spec.rb, spec/features/admin_view_spec.rb, spec/features/collection_spec.rb, spec/features/owner_actions_spec.rb, spec/features/role_view_spec.rb, spec/features/zz_deletion_spec.rb
_Resolves #3619 (and #3590, #3205)_
This improves and simplifies the owner dashboard.
* UI updated so that collections are more easily distinguished with a border, like how works are shown on the collection show page.
* Collection description removed.
* Works list removed.
* "You can add another work under Start A Project" was previously written under work list, now removed.
* Collection privacy added next to the collection title.
* Document sets nested under the collection they belong to instead of listed at the bottom of the dashboard.
* Inactive collections listed separate from active collections, at the bottom of the dashboard.
* Collection progress % completed statistics added (% completed, transcribed, reviewed, indexed).
* Collection progress bars added.
The logic for these last …
=> Simplified owner dashboard and added collection progress bars for #3619

app/controllers/admin_controller.rb, app/controllers/application_controller.rb, app/controllers/collection_controller.rb, app/controllers/concerns/owner_exporter.rb, app/controllers/display_controller.rb, app/controllers/registrations_controller.rb, app/controllers/search_attempt_controller.rb, app/controllers/user_controller.rb, app/models/search_attempt.rb, app/views/admin/searches.html.slim, app/views/collection/show.html.slim, app/views/display/_multi_page.html.slim, app/views/display/_pages_view.html.slim, app/views/search_attempt/show.html.slim, app/views/shared/_breadcrumbs.html.slim, config/locales/admin/admin-en.yml, config/routes.rb, db/migrate/20230804144422_add_collections_and_works_to_search_attempts.rb, db/schema.rb
_Resolves #3730_
This tracks searches on collections by text, works by text, and collections by title/metadata. It does so using the same `SearchAttempt` model used for Find a Project searches. The search results pages are unchanged and remain on the `collection#paged_search` and `collection#show` pages. However, the backend now goes through the `search_attempt#create` action to record the search, and the results pages use this SearchAttempt object to find the search's results.
I also improved  search result click tracking to be much more straightforward and reliable. Clicking on a search result calls a JavaScript method (via `onclick`) which calls a `search_attempt#click` action via AJAX.
Collection/work search results also have breadcrumbs to return to search results once a result is …
=> Track collection and work searches with search attempts for #3730

app/controllers/bulk_export_controller.rb, app/controllers/concerns/export_service.rb, app/helpers/export_helper.rb, app/views/export/index.html.slim, config/locales/export/export-de.yml, config/locales/export/export-en.yml, config/locales/export/export-es.yml, config/locales/export/export-fr.yml, config/locales/export/export-pt.yml, db/migrate/20230814171021_add_collection_notes_to_bulk_exports.rb, db/schema.rb
_Resolves #3738_ 
This adds a bulk export for all notes in a collection, to allow project owners to preserve & review notes.
The export is located on the collection export page:
And here's how the exported CSV file looks, with the Utah Birth Certificates collection as example:
=> Added collection notes bulk export for #3738

app/assets/javascripts/application.js, app/views/deed/list.html.slim
_Resolves #3739_
This is meant to solve filtering/searching collection notes by implementing DataTables which comes with a search. Because the notes list is made by filtering the deed list to only notes, I just edited the deed list to use DataTables.
Here's the notes list, it can quickly be filtered and sorted:
And this also changes the all deeds list:
If we don't want to change the deeds list, I can separate it from the notes list.
=> Implemented DataTables to deed list for #3739

app/views/document_sets/_set_works.html.slim
_Fixes #3769_
Transcribers can't see the 'Remove from set' column anymore:
and the `remove_from_set` form is gone altogether from their HTML. 
The owner view remains the same, functionality intact.
=> Don't let transcribers remove works on docset works list for #3769

app/controllers/deed_controller.rb, app/views/deed/list.html.slim, config/locales/deed/deed-de.yml, config/locales/deed/deed-en.yml, config/locales/deed/deed-es.yml, config/locales/deed/deed-fr.yml, config/locales/deed/deed-pt.yml
This (temporarily?) addresses two issues:
1. All deed & note lists were being truncated to 50 items because the `.paginate` call was mistakenly still being called on them. 
2. If they were not being truncated, there would be major performance issues with loading a large amount of rows without pagination.
The notes list for a collection -- the focus of #3739 -- is still using DataTables & will now load _all_ notes on a collection. I tested this with around 500 entries and had no performance issues.
Deeds lists, and notes lists without a collection, are back to using `will_paginate` as per usual, no DataTables, so there won't be any performance issues on long lists.
=> Only use datatables on collection notes list for #3776

app/controllers/display_controller.rb, app/controllers/search_attempt_controller.rb, app/models/search_attempt.rb, app/views/admin/searches.html.slim, app/views/collection/show.html.slim, app/views/shared/_breadcrumbs.html.slim, db/migrate/20230911200902_add_document_sets_to_search_attempts.rb
_Resolves #3775_
This adds a `document_set_id` field to `SearchAttempts` so that any document sets that are searched on are not coerced into the 
`collection` field. In result, this fixes the bug where searching on a document set can redirect to a search on the _collection_ with the same ID or slug. 
Some of the search attempt logic was also cleaned up & simplified in the process 😊
=> Added document sets to search attempts for #3775

Gemfile, Gemfile.lock, app/controllers/deed_controller.rb, app/controllers/notes_controller.rb, app/datatables/note_datatable.rb, app/views/admin/index.html.slim, app/views/collection/show.html.slim, app/views/deed/list.html.slim, app/views/notes/list.html.slim, config/initializers/ajax_datatables_rails.rb, config/locales/notes/notes-de.yml, config/locales/notes/notes-en.yml, config/locales/notes/notes-es.yml, config/locales/notes/notes-fr.yml, config/locales/notes/notes-pt.yml, config/routes.rb, spec/models/deed_spec.rb
_Resolves #3790_
After implementing DataTables on the notes & deeds list, these pages have performance issues on long lists because all of the rows must be loaded by the server at once.
To fix this, this PR changes the notes DataTable to use [server-side processing](https://datatables.net/manual/server-side). This means that the server only loads the currently displayed rows at once, eliminating the issue for large tables. This also means that all sorting and searching is handled on the server-side instead of the client-side, resulting in a slower UI (but it's consistent over all table lengths!)
I used the [ajax-datatables-rails](https://github.com/jbox-web/ajax-datatables-rails) gem, which handles a majority of the server-side processing. 
I split the deeds list and notes list, so the …
=> Implemented server-side datatables for notes list for #3790

app/helpers/export_helper.rb
Fixes regression introduced by table markup, replacing previous fix for #3809
=> Correct regression for #3809

app/assets/stylesheets/sections/collection.scss, app/models/article.rb, app/views/article/list.html.slim, db/migrate/20231114181654_add_pages_count_to_articles.rb
=> #2095 Include page counts on subject browse

app/views/shared/_osd_div.html.slim
This small PR addresses issue #3247: the bounce-back effect that users experience when dragging the image outside of the viewer area.
The effect is controlled by OpenSeadragons's `visibilityRatio` init argument. In your current setting (visibilityRatio = 1), OpenSeadragon will attempt to bounce the image back to a state where __the viewer shows no empty background.__ Consequently, if users have a narrow viewport set, then attempts to drag the image to an "extreme edge" position  (as reported in issue #3247) can easily lead to this effect.
- user drags the image slightly out of the image
- the inertial bounce-back effect pushes the image back (possibly overshooting the original starting position)
The easiest way to address this is to set `visibilityRatio` to a more relaxed setting, like …
=> "Rebound" effect in OpenSeadragon viewer

app/views/shared/_osd_div.html.slim
This small PR removes the unused `fitBounds` parameter from the OpenSeadragon initialization.
=> Removed 'fitBounds' init parameter

app/controllers/concerns/export_service.rb, app/models/work.rb, app/views/export/facing_edition.html.erb, app/views/export/show.html.erb, app/views/export/tei.html.erb, app/views/export/text.html.erb, app/views/export/transcript.html.erb
Closes #4019 by suppressing blank page text exports in *all formats*.
=> Suppress text exports for blank pages in #4019

app/views/transcribe/display_page.html.slim
Addresses #4037.  Removes JS error for non-Codemirror transcription.  
To test loading side-by-side pages with headers once deployed.
=> Mostly fixes regression caused by #4037; removes js error

app/controllers/display_controller.rb
After some investigation, I found an empty string was passed into highlight function. 
I added search_string to else case.  It works well now! 
Closes #4098
=> Fixed highlight bug on #4098

app/assets/config/manifest.js, app/assets/javascripts/application.js, app/assets/javascripts/select_all.js, app/views/document_sets/index.html.slim, app/views/document_sets/settings.html.slim, app/views/sc_collections/explore_collection.html.slim, spec/features/document_sets_spec.rb
Added select_all.js
USAGE:
1. For the select_all checkbox, add `data-select-all="#{unique_identifier_class}"`, where the value unique_identifier_class is arbitrary.
2. For all checkboxes to be affected, add the unique_identifier_class
=> 3484 - Select all works on document set edit screen

app/views/shared/_handsontable.html.erb
=> 3053 - wrap column for long text

app/models/collection.rb, app/models/work.rb, app/validators/html_validator.rb, config/locales/activerecord/activerecord-de.yml, config/locales/activerecord/activerecord-en.yml, config/locales/activerecord/activerecord-es.yml, config/locales/activerecord/activerecord-fr.yml, config/locales/activerecord/activerecord-pt.yml, config/locales/errors/errors-de.yml, config/locales/errors/errors-en.yml, config/locales/errors/errors-es.yml, config/locales/errors/errors-fr.yml, config/locales/errors/errors-pt.yml
Based on issue #4074 
Added a reusable html_validator that utilizes `REXML::ParseException` to handle invalid html syntax.
Usage:
```
class YourModel < ApplicationRecord
validates :your_field, html: true
```
Optionally we can pass specific messages (useful for model-specific translations):
```
class YourModel < ApplicationRecord
validates :your_field, html: { message: 'Custom error message' }
```
html_validator component can have more features in future such as adding validation for limiting number of characters EXCLUDING html tags so I decided in favor of making it it's own validator class.
=> 4074 - Validate html before saving

app/views/user_mailer/added_note.html.slim, app/views/user_mailer/added_note.text.erb, app/views/user_mailer/nightly_user_activity.html.slim, app/views/user_mailer/nightly_user_activity.text.erb
=> 2527 - Activity emails shouldn't link to "transcribe" page

app/datatables/note_datatable.rb, app/views/collection/show.html.slim
#1682 
It seems the issue is regarding orphaned notes (when page_id: nil).
Approach done here is to render plain text instead of link when note.page.nil
BUT to be more elaborate, need answer to some of these questions:
SHOULD we allow page_id to be nullable in note? (In my local db dump there are 0 notes with page_id: nil. Looking at the notes model though it seems that it can be made for a work and not a page, not sure how this all works so please clarify).
=> 1682 - Error when viewing notes with no page

app/helpers/devise_helper.rb, config/locales/devise/devise-de.yml, config/locales/devise/devise-en.yml, config/locales/devise/devise-es.yml, config/locales/devise/devise-fr.yml, config/locales/devise/devise-pt.yml
The error is likely due to invalid reset password token (maybe expired).
I believe we need a custom message here. Only saying `Reset password token is invalid`, which would be the default message, is lacking in prompting the user what was the error to begin with. I suggest overriding the message format when it is about reset_password_token errors to this:
```
Your reset password link is invalid or expired. Request another reset password to continue.
```
Let me know your thoughts @benwbrum @saracarl
=> 4189 - Missing message when user resets password

app/models/deed.rb
The activity stream on `collection#show` is cached on `@collection.most_recent_deed_created_at`, however this value was not being updated for several collections.  
On further review, this was caused by the addition of validations to check for valid XHTML in `collection.intro_block`.  Since [the after_save deed callback](https://github.com/benwbrum/fromthepage/blob/development/app/models/deed.rb#L90-L100) was calling `update`, validations were being checked.  If a collection failed validation (as was the case for these collections), we were not updating the column on the record.
Since there is no way a volunteer can address validation failures on `collection.intro_blcok` when they are merely transcribing a page, I've changed this logic to `update_columns`, which by-passes validations.
=> Bypass validations when updating most recent deed date for #4182

app/controllers/transcribe_controller.rb, app/views/transcribe/assign_categories.html.slim, config/locales/transcribe/transcribe-de.yml, config/locales/transcribe/transcribe-en.yml, config/locales/transcribe/transcribe-es.yml, config/locales/transcribe/transcribe-fr.yml, config/locales/transcribe/transcribe-pt.yml
Discussions so far with @benwbrum 
I'm playing around the functionality. Correct me in if I am wrong here, but I think these should be the cases:
1. I want to go back and make some changes
a. We click on cancel button. This should not assign a category, BUT I would assume this should also NOT create the subject, otherwise why cancel in the first place.
2. I want to save my changes
a. We click on save or continue button. THIS should assign categories and redirect back to same page (in case we want to edit some texts, add new subjects, etc).
b. Regardless if they assign the category here, the subject SHOULD persist.
3. I want to save and continue to next page
a. It creates and assigns subject and redirects to next page
I believe this should be the case, as was described by the user on the …
=> 2313 - Abandon subject without losing transcription

.github/workflows/ci.yml, Gemfile, Gemfile.lock, app/controllers/concerns/export_service.rb, app/controllers/export_controller.rb, app/helpers/abstract_xml_helper.rb, spec/requests/export_controller_spec.rb
https://github.com/jgm/pandoc/issues/2330
Pandoc seems to not support page break when converting from `latex` to `pdf`.
There are existing lua filters as workaround for this, but nothing made yet for a pdf output.
Ironically, our old approach of directly uploading from `md` to `pdf` supports `\newpage` and other tags, but we go back to initial issue of unsupported font  for \textsinglequote. So this PR will revert to old approach and fix the initial issue at #4297 
After much research on the matter, I have pinpointed the error to Xelatex being not fully compatible with fonts (fontenc for example, which is what is being used for pdfs). To resolve this I switched out the pdf engine from `xelatex` to `pdflatex` and everything worked correctly.
@benwbrum @saracarl is there any particular …
=> 4302 - Missing page breaks on facing pdf

app/helpers/abstract_xml_helper.rb
Closes #4319
(It turns out that this was caused by calling `gsub` on elements that had `nil` `.text`)
=> #4319: only gsub if there is text

app/assets/stylesheets/application.scss
This takes on a different, safer approach.
We add 'bs' as the namespace whenever we want to use bootstrap css. This will preserve all existing css classes we have.
@benwbrum @saracarl
=> 4264 - Bootstrap css classes not working

lib/tasks/iiif_collection_import.rake
This addresses #4348 by creating a rake task that can be passed an OCLC paged collection manifest on the command line, and the DB ID of the collection to import into.
Example:
```
rake fromthepage:import_paged_iiif_collection['https://cdm15138.contentdm.oclc.org/iiif/2/p15138coll54/manifest.json',32000684]
```
=> Stopgap rake script for #4348

app/views/system_mailer/config_test.html.erb, app/views/system_mailer/config_test.text.erb
There was a typo in the HTML mailer view, an extra 'a'. And the link that suggests it goes to the collection list is a link to the uploads. This PR fixes both.
=> Replace link in configuration test mailer views with actual collection list link

app/views/document_sets/_edit.html.slim, app/views/user/update_profile.html.slim
It bothered me that "current URL" items in forms for updating a user profile or document set include `www.`, whereas our FromThePage does not have that. In fact, we don't have `www.` in our DNS records.
This PR updates the views to remove it. Based on a comment by @WillNigel23 on #4397 I used the URL helper where available, but I could not find a route for the document set.
=> Remove hardcoded 'www.' from "current URL"s in forms

spec/features/archive_import_spec.rb, spec/features/export_spec.rb, spec/features/field_based_spec.rb, spec/features/forum_spec.rb, spec/features/metadata_description_spec.rb
Capybara provides some useful methods for E2E testing. These methods also wait automatically for target elements to appear. Therefore, using the provided methods instead of sleep usually makes tests more stable. For this reason, I tried replacing the existing code with these methods.
e.g.) 
[page.accept_confirm](https://rubydoc.info/github/jnicklas/capybara/Capybara/Session:accept_confirm) method
=> Use the appropriate Capybara methods.

app/views/contact/form.html.slim, app/views/contact/send_email.html.slim, app/views/static/at.html.slim, app/views/static/meredithsstory.html.slim, app/views/static/natsstory.html.slim, app/views/static/software.html.slim, app/views/static/splash.html.slim
This fixes #4452 by adding the condition for inclusion of the `mixpanel.track` calls to the views that did not have this.
=> Call Mixpanel only when enabled

app/models/collection.rb, app/models/page.rb, app/models/work.rb, lib/elastic/schema/collection.json, lib/elastic/schema/page.json, lib/elastic/schema/template.json, lib/elastic/schema/work.json
- Drop wildcard from identifier analysis as it can cause match-all behavior due to drop purewords filter.
- Expand terms with underscores into `title.no_underscores` and use in search.
=> Schema patches:
