benwbrum/fromthepage

- app/views/export/show.html.erb
- config/environments/development.rb
- config/environments/production.rb
removed encoding that was causing an exception, since we now UTF
related to Issue #281
> remove ISO encoding on display

- app/assets/javascripts/application.js
- app/assets/stylesheets/sections/page.scss
- app/controllers/collection_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/transcribe_controller.rb
- app/models/user.rb
- app/views/admin/uploads.html.slim
- app/views/dashboard/_editor_header.html.slim
- app/views/dashboard/_guest_header.html.slim
- app/views/dashboard/_owner_header.html.slim
- app/views/dashboard/guest.html.slim
- app/views/shared/_page_tabs.html.slim
- app/views/statistics/collection.html.slim
- app/views/transcribe/display_page.html.slim
- config/locales/devise.en.yml
- config/routes.rb
All the changes that have been made in the tbl73-dev branch - some of the earlier ones have already been reviewed but not merged.  The list includes issues 354, 357, 365, 358, 366, 312, 374, 340, 387, and 383.
> tbl73-dev branch

- app/controllers/collection_controller.rb
- app/models/category.rb
Add default categories of People and Places when the collection is created.
> issue #403 - categories branch

- app/controllers/dashboard_controller.rb
- app/views/dashboard/watchlist.html.slim
Further code changes to resolve the 500 internal server error for specific cases in the redirect to the editor dashboard.
> issue 442 - editor dashboard redirects

- db/migrate/20161014193619_remove_bad_sccollection_data.rb
Added migration to delete bad ScCollection data to resolve issue #348 on UT's server.
> issue #348

- db/migrate/20101124091725_create_page_blocks.rb
Changed the copy in the migration for the splash page in the open-source product.
> Open source landing pages, issue #336

- app/controllers/dashboard_controller.rb
- app/views/collection/_contributors_body.html.slim
- app/views/collection/show.html.slim
- app/views/dashboard/_editor_header.html.slim
- app/views/dashboard/omeka.html.slim
- app/views/dashboard/startproject.html.slim
- app/views/dashboard/upload.html.slim
- app/views/dashboard/watchlist.html.slim
- app/views/ia/manage.html.slim
- app/views/layouts/application.html.slim
- app/views/omeka_items/show.html.slim
- app/views/shared/_collection_tabs.html.slim
- app/views/static/about.html.slim
- app/views/static/faq.html.slim
- app/views/static/transcribe_help.html.slim
- app/views/statistics/collection.html.slim
- app/views/work/edit.html.slim
Multiple wording changes to the UI.
> Wording, issue #406, #410, #422

- app/controllers/display_controller.rb
- app/models/ia_work.rb
- app/views/display/_multi_page.html.slim
- app/views/page/edit.html.slim
- app/views/page_version/show.html.slim
- app/views/work/versions.html.slim
Fixed transcription/edit statistics for works imported from internet archive.  Changed UI/wording for works that need OCR correction when imported.
> Issues #411 and #447

- app/models/ia_work.rb
- db/migrate/20161020181450_change_ia_works_description_size.rb
Truncate the description field on import from IA works.
> Issue #448, IA Import Error

- app/controllers/collection_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/page_controller.rb
- app/helpers/add_work_helper.rb
- app/models/work.rb
- app/views/collection/empty_work.html.slim
- app/views/collection/upload.html.slim
- app/views/dashboard/_empty.html.slim
- app/views/dashboard/_new_work.html.slim
- app/views/dashboard/_owner_header.html.slim
- app/views/dashboard/_upload.html.slim
- app/views/dashboard/empty_work.html.slim
- app/views/page/new.html.slim
Removed create work from Action menu, added the ability to create an empty work to the Start a Project tab.
> Issue #460

- app/controllers/dashboard_controller.rb
- app/models/collection.rb
- app/models/work.rb
- app/views/dashboard/guest.html.slim
Corrected guest activity list; also added scopes to work and collection to find unrestricted.
> fixed guest dashboard, issue #462

- app/controllers/article_controller.rb
- app/controllers/transcribe_controller.rb
- app/models/article.rb
- app/models/page.rb
- app/models/page_article_link.rb
- app/models/xml_source_processor.rb
- app/views/article/edit.html.slim
- app/views/article/show.html.slim
- app/views/transcribe/assign_categories.html.slim
- app/views/transcribe/display_page.html.slim
- app/views/transcribe/translate.html.slim
- spec/features/editor_actions_spec.rb
- spec/features/link_spec.rb
- spec/features/linking_spec.rb
- spec/fixtures/articles.yml
- spec/fixtures/articles_categories.yml
- spec/fixtures/page_article_links.yml
- spec/fixtures/pages.yml
- spec/fixtures/works.yml
This covers a number of different issues related to subject linking - problems with bad data in links ( #7, #473), working with subjects ( #388, #478), links in translations ( #475, #497), subject versioning ( #196 ), and tests for those issues.
> Subject linking

- app/controllers/iiif_controller.rb
- config/routes.rb
- db/migrate/20170318205337_add_index_on_notes.rb
- db/schema.rb
Still to do -- profiles for retrieving exports and connecting to transcription services
> Added redirector for imported IIIF IDs

- app/controllers/iiif_controller.rb
- app/models/collection.rb
I believe that this may fix the `iiif/for` controller.
> Fix bug in unescaped URLs; add originating collection ID

- .gitignore
- lib/tasks/ingestor.rake
I added sorts for the various steps in the upload process, and updated .gitignore.
> #587 sort compressed files and #17

- app/views/admin_mailer/email_stats.html.slim
- app/views/devise/registrations/new.html.slim
Also adds owner designation to the admin emails.
> 641 - user sign in wording

- app/controllers/dashboard_controller.rb
- app/controllers/work_controller.rb
- app/helpers/add_work_helper.rb
- app/helpers/contributor_helper.rb
- app/models/deed.rb
- app/models/ia_work.rb
- app/models/omeka_item.rb
- app/models/sc_manifest.rb
- app/views/collection/_contributor_activity.html.slim
- app/views/deed/_deed.html.slim
- lib/tasks/ingestor.rake
- spec/features/add_data_spec.rb
- spec/features/document_sets_spec.rb
- spec/features/owner_actions_spec.rb
- spec/features/zz_deletion_spec.rb
This also involved creating a new deed when a work is added or moved into another collection.
> #205 Hide defunct collections

- app/controllers/collection_controller.rb
- app/controllers/document_sets_controller.rb
- app/controllers/user_controller.rb
- app/controllers/work_controller.rb
- app/models/document_set_statistic.rb
- app/views/collection/edit.html.slim
- app/views/document_sets/_edit.html.slim
- app/views/document_sets/settings.html.slim
- app/views/user/update_profile.html.slim
- app/views/work/edit.html.slim
- spec/features/url_spec.rb
> Issues #679, #680, #681

- lib/image_helper.rb
- lib/workers/image_transformer_worker.rb
This was a pretty small change, but I don't know what additional image processing testing might be needed - I uploaded a work and added images to works/collections, in addition to running the tests.
> #465 - Rmagick deprecation warning

- app/controllers/transcribe_controller.rb
- app/models/work_statistic.rb
The statistics need to be double-checked - I think I've got them correctly recalculating only the necessary stats, but they get confusing.
> #730 and #731, for performance improvement on save

- app/models/sc_manifest.rb
- app/views/work/versions.html.slim
See issue for further comments.
> #747 - deeds for IIIF works

- app/models/user.rb
- db/schema.rb
- spec/features/user_deletion_spec.rb
You can assign this to me once the merge conflicts are resolved.
> Delete dependent records on user deletion #758

- Gemfile.lock
- app/views/export/show.html.erb
- db/schema.rb
The output has been reviewed by Laura, and is ready to merge.
> Added translation to XHTML export for #777

- .travis.yml
- config/database.travis.yml
> #721 initial travis-ci configuration

- app/views/layouts/application.html.slim
- app/views/user/profile.html.slim
- spec/features/editor_actions_spec.rb
- spec/features/owner_actions_spec.rb
- spec/features/url_spec.rb
This is just the cleanup piece of the owner/user homepage changes - the carousel etc will be handled at a later point.
> #740 owner homepage cleanup and #621 blog link

- app/controllers/iiif_controller.rb
Note - I wasn't really able to test this through Mirador/Universal viewer, because my dev server isn't public.
> #762 Broken riiif images

- app/models/tex_figure.rb
- config/environments/development.rb
- config/environments/production.rb
- lib/tasks/config_test.rake
Addressing issues in #981 
More logging for rake task
Check setup for LaTeX
New path variable for TeXLive installation
Conditionalize styles for Peirce, chemical formulae and others.
> Fault tolerant LaTeX support

- app/models/ia_work.rb
This is needed for UT's Alcedo, so we need to get it into `master` as soon as we can.
> Use shorter book id for slug

- travis/.travis_mysql57.sh
> Changed keyserver

- app/models/user.rb
- app/views/user/update_profile.html.slim
- db/migrate/20180717215604_add_user_orcid.rb
- gemfiles/Gemfile.mysql57
Closes #1082 and makes ready for #1081
> Adds contributor ORCID to user model/profile

- app/views/transcribe/assign_categories.html.slim
Stopgap for UT's installation.
> Don't blow up if we can't find the subject title in the text

- app/controllers/collection_controller.rb
Closes #1077
Adds the count of the following to the active contributor CSV export:
- Pages transcribed
- Page edits
- Pages Translated
- OCR Corrections
- Notes Added
> Adds user stats to Active Collaborators export CSV

- app/views/notes/_note.html.slim
- spec/features/editor_actions_spec.rb
Closes #1182 
Allows Owners to delete Notes. Only the note creator can edit.
> Owners are able to delete notes

- app/controllers/work_controller.rb
- app/views/work/edit.html.slim
- spec/features/owner_actions_spec.rb
> 1317 bad work id param

- app/models/ia_work.rb
This eliminates unused code that was breaking on long subject imports.  It needs to be merged into `master` as well and deployed to NYBG.
> Eliminate unused code that broke on long subjects.

- app/controllers/admin_controller.rb
- app/models/article.rb
- app/models/article_version.rb
- app/models/flag.rb
- app/models/note.rb
- app/models/page_version.rb
- app/models/user.rb
- app/views/admin/_header.html.slim
- app/views/admin/expunge_confirmation.html.slim
- app/views/admin/flag_list.html.slim
- app/views/admin/settings.html.slim
- db/migrate/20190712114547_create_flags.rb
- db/migrate/20190713144825_blacklist_pageblock.rb
- db/schema.rb
- lib/flagger.rb
- lib/tasks/flag_abuse.rake
- spec/factories/flags.rb
- spec/features/admin_view_spec.rb
- spec/features/editor_actions_spec.rb
- spec/models/flag_spec.rb
Closes #1398 by adding a feature to find, flag, and delete malicious content.
> 1398 flag abuse

- app/views/export/index.html.slim
- config/routes.rb
> IIIF: add API links

- app/models/work.rb
- app/views/work/edit.html.slim
- spec/features/work_settings_spec.rb
Closes #1388
With tests.
(I also updated some form labels that were sentence cased)
> Adds OCR checkbox to work settings tab

- app/controllers/application_controller.rb
- app/controllers/collection_controller.rb
The show method assumes there's always a collection to show. Check
whether collection is nil, and if it happens to be, return the 404 page.
Fixes: #1423
> collection: fix bad record id

- Gemfile.lock
> 1478 bump rmagick

- app/views/dashboard/_empty.html.slim
- app/views/dashboard/_new_work.html.slim
- app/views/dashboard/_upload.html.slim
- spec/features/zz_iiif_collection_spec.rb
> dashboard: improve usability for Start a Project

- app/helpers/abstract_xml_helper.rb
> export: supress spans in XHTML export

- spec/helpers/abstract_xml_helper_spec.rb
- spec/support/devise.rb
Initial tests for AbstractXmlHelper (xml_to_html).
Fixes: #1511
> AbstractXmlHelper: add tests

- app/views/export/index.html.slim
> iiif: fix broken url

- app/views/shared/_iiif_div.html.erb
> iiif: allow images to be rotated

- app/views/dashboard/_empty.html.slim
- app/views/dashboard/_new_work.html.slim
- app/views/dashboard/_upload.html.slim
- spec/features/add_data_spec.rb
- spec/features/archive_import_spec.rb
- spec/features/collection_spec.rb
- spec/features/import_data_spec.rb
- spec/features/owner_actions_spec.rb
- spec/features/zz_iiif_collection_spec.rb
This improves on #1447 and #1484 by actually making titles clickable.
Fixes: #1447.
> dashboard: make titles clickable

- app/models/collection.rb
- app/models/document_set.rb
- app/views/dashboard/landing_page.html.slim
> dashboard: include owner names when searching

- app/views/transcribe/display_page.html.slim
> transcribe: hide still editing ajax spinner

- app/controllers/admin_controller.rb
- app/models/user.rb
- app/views/admin/edit_user.html.slim
- config/routes.rb
- spec/features/admin_view_spec.rb
- spec/fixtures/users.yml
> admin: add downgrade owner account

- lib/tasks/ingestor.rake
> Fixes #1596 by adding GC.start to loop

- app/controllers/sc_collections_controller.rb
- app/views/sc_collections/explore_manifest.html.slim
> Fix indentation for IIIF manifest imports

- config/initializers/slim.rb
This reverts commit 36ee86a6f662b496894574fc433f905f41616973.
> Revert "Disable prettyfied html in development"

- app/views/admin/user_list.html.slim
> admin: fix user search

- app/views/dashboard/_upload.html.slim
- spec/features/owner_actions_spec.rb
> dashboard: limit uploads for trial users

- .travis.yml
- app/controllers/application_controller.rb
- app/controllers/export_controller.rb
- app/models/user.rb
- app/views/admin/edit_user.html.slim
- app/views/devise/registrations/edit.html.slim
- app/views/devise/registrations/new.html.slim
- app/views/export/tei.html.erb
- db/migrate/20200207034944_rename_print_name_to_real_name.rb
- db/schema.rb
- spec/features/devise_spec.rb
- spec/features/guest_spec.rb
- spec/features/role_view_spec.rb
- spec/features/spam_user_spec.rb
- spec/fixtures/users.yml
> 1610 attribution name for users

- app/controllers/application_controller.rb
> Fix incorrect record from being retrieved

- app/controllers/collection_controller.rb
- spec/features/zz_iiif_collection_spec.rb
> collection: show all works when the list is empty

- app/assets/stylesheets/sections/work.scss
- app/controllers/collection_controller.rb
- app/views/collection/edit.html.slim
> collection: add restrict transcribed works button

- app/helpers/abstract_xml_helper.rb
> Fixed #1767 by adding a space for needs review pages action

- app/views/collection/show.html.slim
Thumbnail picture on works is now a link.
> work thumbnail is now a link

- app/views/display/display_page.html.slim
- app/views/notes/_notes.html.slim
- app/views/transcribe/display_page.html.slim
- app/views/transcribe/translate.html.slim
> changed notes to notes and questions

- lib/tasks/ingestor.rake
Upload metadata files in the same folder as PDFs.
Closes #1789
> 1789 metadata yml pdf

- app/controllers/admin_controller.rb
- app/views/collection/_contributors_body.html.slim
added support@fromthepage.com to the list of contributors
> 1278 add support email

- app/helpers/abstract_xml_helper.rb
- spec/helpers/abstract_xml_helper_spec.rb
> Fixes #1812 by re-adding hyphens

- app/helpers/collection_helper.rb
- app/views/collection/show.html.slim
> Fixed 1842 by showing blanked pages as green

- lib/tasks/ingestor.rake
> Fixed #1844 by removing outdated assumption

- app/controllers/application_controller.rb
- app/controllers/export_controller.rb
- app/helpers/export_helper.rb
- app/views/export/tei.html.erb
This adds categorization to subjects, fixes broken export links, and fixes sub-category support within the TEI export.
> Add categorization to subjects and fix #1751 for bad slugs in works

- app/helpers/add_work_helper.rb
- lib/tasks/ingestor.rake
Had to make a new pull request to finish issue 1828 because it wouldn't let me put the changes in here into the original. Sorry. I would appreciate someone showing me how to do it right.
> remove new upload emails finish

- config/routes.rb
> dashboard: fix regression due to missing route

- app/controllers/export_controller.rb
- app/helpers/export_helper.rb
> Fixes #1902 regression

- config/locales/dashboard/dashboard-en.yml
> dashboard: fix regression due to missing locale

- config/locales/deed/deed-en.yml
> i18n: add missing locales

- app/helpers/export_helper.rb
This fixes #1918 by escaping subject titles.
> Fixes #1918 by escaping subject titles

- app/views/collection/show.html.slim
> Fixes #1897 by conditionalizinog pages

- app/views/deed/_deed.html.slim
> deed: fix regression with domain names

- app/models/page.rb
> 1812 retain dash in export

- app/models/page.rb
> Fixes #1943 by converting div and br to newlines on plaintext export

- app/views/admin/_header.html.slim
- lib/tasks/ingestor.rake
> admin tabs regression fix

- app/controllers/article_controller.rb
- config/routes.rb
> 1919 combining subjects doesnt

- app/controllers/document_sets_controller.rb
- app/views/document_sets/index.html.slim
- spec/features/add_data_spec.rb
> Fixes #1952 by rewriting work-set assignment

- app/controllers/article_controller.rb
Fixes #1497 by refactoring query
> Subject Page Performance

- config/application.rb
> i18n: add English fallback for missing translations

- app/controllers/collection_controller.rb
- db/migrate/20200819161133_clean_duplicate_collection_owners.rb
> Fixes #1992 by refactoring logic and cleaning data

- app/assets/stylesheets/sections/collection.scss
- app/assets/stylesheets/sections/work.scss
Make image size explicit for page thumbnails for #2011
> Resolves #2011 by fixing page thumbnail image width to 8em

- app/models/collection.rb
> Fixes #2017 by searching work metadata

- app/controllers/iiif_controller.rb
> iiif: replace _path with _url for endpoints

- app/views/layouts/application.html.slim
- spec/features/role_view_spec.rb
> layout: hide dashboard link for guest users

- app/controllers/article_controller.rb
> Resolves #2035 by renaming permitted param

- app/models/deed_type.rb
- lib/ahoy_activity_utils.rb
- lib/tasks/contributors.rake
Include activity by users who have done OCR correction; also allow data remediation by replacing old data with new calculations.
Resolves #2044
> Fixes #2044 by including OCR correction in ahoy summaries

- lib/contentdm_translator.rb
> Updates arguments for #2051

- app/models/page.rb
> Increase thumbnail size by 4 for #2053

- app/controllers/deed_controller.rb
- app/views/collection/show.html.slim
- config/routes.rb
> Resolves #1522 by linking to a new notes feed

- config/routes.rb
> Add IIIF collections route

- app/views/notes/_notes.html.slim
> notes: reset form after updating it

- app/views/notes/_note.html.slim
- config/locales/notes/notes-en.yml
- config/locales/notes/notes-es.yml
- config/locales/notes/notes-pt.yml
Looks like this:
If it is not okay, I can figure something else out.
> Added seperation of name and time in notes

- app/helpers/export_helper.rb
- app/views/devise/sessions/new.html.slim
- app/views/export/tei.html.erb
> 2087 add geo to non place subjects in tei

- app/controllers/application_controller.rb
> Fix error message on private collections for #2101

- app/models/page.rb
- app/views/devise/sessions/new.html.slim
- config/routes.rb
- lib/contentdm_translator.rb
- lib/search_translator.rb
- spec/features/editor_actions_spec.rb
- spec/features/full_text_search_spec.rb
- spec/http-mocks/cdm/bad_iiif_manifest.yml
- spec/http-mocks/cdm/midpoint-repository.yml
- spec/http-mocks/cdm/midpoint-shelwater-collection.yml
- spec/http-mocks/cdm/midpoint-shelwater-item.yml
- spec/http-mocks/iiif/cambridge_hebrew_mss.yml
Fixes newline problems in plaintext searchable exports.
> 1712 fix newline whitespace plaintext

- app/views/article/show.html.slim
- config/routes.rb
- spec/features/document_sets_spec.rb
- spec/http-mocks/cdm/bad_iiif_manifest.yml
- spec/http-mocks/cdm/midpoint-repository.yml
- spec/http-mocks/cdm/midpoint-shelwater-collection.yml
- spec/http-mocks/cdm/midpoint-shelwater-item.yml
- spec/http-mocks/iiif/cambridge_hebrew_mss.yml
> Addressed #2102 by moving display_search from GET to POST

- app/controllers/export_controller.rb
- lib/contentdm_translator.rb
> Fixed #2144 by creating a log directory if it does not already exist

- app/views/transcribe/display_page.html.slim
> Bad message for questions and notes

- app/controllers/page_controller.rb
> Fixes 2148 by handling Rails 6 file types

- app/models/user.rb
> Avoid 500 errors for conflicting logins; update sso issuer for #2146

- app/models/xml_source_processor.rb
- spec/features/editor_actions_spec.rb
> Fixes #2155 by testing for hyphens following words

- app/models/deed.rb
> Fixes #2175 by using correct context for messages

- .travis.yml
- app/models/document_set.rb
- spec/features/document_sets_spec.rb
> Address #2168 by ordering works in sets by titles

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/user_controller.rb
- app/views/user/update_profile.html.slim
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt.yml
- db/migrate/20201128180552_add_preferred_locale_to_user.rb
- db/schema.rb
Closes #1926.  This implements an interface language on the user profile, which takes priority.  If no language is set for a user, we use the user's browser settings.
> 1926 locale selection

- app/views/display/display_page.html.slim
- spec/features/zz_deletion_spec.rb
> 2193 page caching hides osd

- app/views/transcribe/display_page.html.slim
Resolves #2221 and addresses one point of #2222
> 2221 long lines etc

- app/helpers/abstract_xml_helper.rb
> Address #2225 by rendering LB in table cells

- app/controllers/dashboard_controller.rb
> 2231 findaproject page does not show owners with no document sets

- Gemfile
- Gemfile.lock
- app/controllers/metadata_controller.rb
- app/models/metadata.rb
- app/models/work.rb
- app/views/metadata/upload.html.slim
- config/locales/metadata/metadata-en.yml
- spec/features/collection_metadata_spec.rb
Contains some wording improvements.
> Fixes #2211 and refactors some metadata upload

- app/models/user.rb
- spec/features/admin_view_spec.rb
> Resolves #2213 by searching real name and email

- app/views/user/profile.html.slim
- spec/features/user_profile_spec.rb
> Fix messages link for #2207

- app/views/transcribe/display_page.html.slim
Enables advanced editor for two works
Adds project-specific button support (if editor is enabled) for KHS, CWRGM, StanfordLibraries
> Add some hard-coded project-specific buttons for #2198

- app/views/article/show.html.slim
> Use new-style route for #2257

- app/helpers/abstract_xml_helper.rb
- app/helpers/export_helper.rb
- app/models/page.rb
- app/views/transcribe/display_page.html.slim
> Add reg/orig tag for #2263

- app/assets/stylesheets/base/helpers.scss
- app/helpers/abstract_xml_helper.rb
- app/helpers/export_helper.rb
- app/models/page.rb
- app/views/transcribe/display_page.html.slim
Adds a new `add` element for #2266 but does not close the issue.
> 2266 add tag for folger

- app/controllers/export_controller.rb
- app/controllers/iiif_controller.rb
- app/helpers/export_helper.rb
- config/routes.rb
Opens TEI and HTML exports for private collections with open APIs
> 2274 open api for tei html exports

- app/assets/javascripts/application.js
- app/assets/stylesheets/sections/collection.scss
- app/views/bulk_export/new.html.slim
- app/views/export/index.html.slim
> Bulk export UI

- app/assets/javascripts/application.js
- app/controllers/bulk_export_controller.rb
- app/controllers/export_controller.rb
- app/views/bulk_export/new.html.slim
- app/views/export/index.html.slim
Re #2295 - Fixed for both Export Individual Works and Export All Works
> Hide export spinner

- app/controllers/application_controller.rb
- app/controllers/iiif_controller.rb
- app/controllers/user_controller.rb
- app/models/user.rb
- app/views/user/_owner_profile.html.slim
- app/views/user/api_key.html.slim
- app/views/user/profile.html.slim
- config/locales/user/user-en.yml
- config/routes.rb
- db/migrate/20210121203828_add_api_key_to_user.rb
Resolves #2289 
CC @bencomp and @mikeapp
> Create API key and key-based authentication for #2289

- app/assets/stylesheets/components/shared.scss
- app/helpers/abstract_xml_helper.rb
- app/helpers/export_helper.rb
- app/models/page.rb
- app/views/transcribe/display_page.html.slim
- lib/search_translator.rb
This is part of (but does not resolve) #2266
> New abbr tag and better handling of abbreviation display for #2266

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/bulk_export_controller.rb
- app/controllers/application_controller.rb
- app/models/bulk_export.rb
- app/models/user.rb
- config/routes.rb
Implements a new bulk export API, closing #1449.
> New bulk export API for #1449

- db/migrate/20210130132501_add_index_to_page_status.rb
- db/migrate/20210131215326_add_index_to_article_categories.rb
- db/schema.rb
> Add index for #2316

- app/assets/javascripts/application.js
- app/views/article/edit.html.slim
- app/views/transcribe/assign_categories.html.slim
> Resolves #2352 by loading document set when assigning categories

- app/controllers/notes_controller.rb
> Fixes #2364 by passing html format to renderer

- app/assets/stylesheets/sections/page.scss
Re #2357. Small and easy fix, should be merged after #2349.
> Change editor font

- app/helpers/transcribe_helper.rb
> Escape parens in link text for #2379

- app/assets/stylesheets/sections/page.scss
> Fix Safari scrolling issue

- app/helpers/abstract_xml_helper.rb
Resolves #2380.  Resolves #2342.
> No empty pop-up for reg/expan with no attribute

- app/helpers/abstract_xml_helper.rb
- app/models/editor_button.rb
- config/locales/collection/collection.en.yml
- config/locales/shared/shared-en.yml
> Added head tag for Folger EMROC #2266

- app/helpers/collection_helper.rb
Closes #2377.  Note that substantial performance improvements could be made with more time and effort.
> Use the document set for start transcribing button #2377

- db/migrate/20210220180026_clean_orphan_page_versions.rb
- db/schema.rb
Resolves #2392 though I still don't know why the orphan records are getting created.
> 2392 error displaying deleted pages

- app/helpers/export_helper.rb
> Fixed #2391 with better return value

- app/controllers/category_controller.rb
- app/views/article/list.html.slim
- app/views/category/add_new.html.slim
- app/views/category/edit.html.slim
This closes #2424.  It does not fix #2425.
> Fixes #2424 by using slugs instead of IDs

- app/controllers/admin_controller.rb
- app/models/user.rb
- app/views/admin/settings.html.slim
Adds a new email denylist.  #2400
> Fixes 2400 to reduce potential abuse

- lib/contentdm_translator.rb
- spec/features/import_data_spec.rb
- spec/models/contentdm_translator_spec.rb
> Implment new IIIF URI for CONTENTdm #2454

- app/assets/stylesheets/components/shared.scss
- app/assets/stylesheets/sections/collection.scss
- app/models/page.rb
- app/views/shared/_handsontable.html.erb
- app/views/transcribe/display_page.html.slim
- app/views/transcription_field/_column_form.html.slim
- app/views/transcription_field/_field_layout.html.slim
- app/views/transcription_field/_line_form.html.slim
- app/views/transcription_field/_new_column_form.html.slim
- app/views/transcription_field/_new_field_form.html.slim
- app/views/transcription_field/edit_columns.html.slim
- app/views/transcription_field/edit_fields.html.slim
- config/locales/transcription_field/transcription_field-en.yml
Re #2343 - Please test it very carefully!
I've updated markup / styles for the Fields tab - forms to configure fields and spreadsheet options. Here everything should be fine or at least better (I hope). But the handsontable plugin is very complicated, so I just tuned it a little. I would not surprise if I did something wrong or something got worse, so once again - test it carefully please.
> Spreadsheet editor UI fixes

- app/models/page.rb
> Fixes #2459 for files with no extension

- app/views/transcribe/display_page.html.slim
Reverts benwbrum/fromthepage#2462
> Revert "Keep buttons at the top with a long conventions text"

- app/controllers/bulk_export_controller.rb
- app/controllers/concerns/export_service.rb
- app/controllers/export_controller.rb
- app/helpers/export_helper.rb
- app/views/bulk_export/new.html.slim
- app/views/export/index.html.slim
- config/locales/export/export-en.yml
- config/routes.rb
- db/migrate/20210401191543_add_work_metadata_csv_to_bulk_export.rb
- db/schema.rb
> Adds a new work metadata export for #2367

- app/assets/stylesheets/sections/page.scss
- app/helpers/transcription_field_helper.rb
- app/views/shared/_handsontable.html.erb
- app/views/transcribe/display_page.html.slim
- app/views/transcription_field/_field_layout.html.slim
- spec/features/field_based_spec.rb
Fixes #2464 and contains improvements for the field based transcriptions
> Spreadsheet and field mode fixes

- lib/contentdm_translator.rb
> Change resolution of dm records during exports for #2468

- app/views/shared/_handsontable.html.erb
> Handle artifacts of renamed columns for #2484

- app/controllers/transcription_field_controller.rb
- app/models/page.rb
- app/views/shared/_handsontable.html.erb
- app/views/shared/_osd_div.html.slim
- app/views/transcription_field/choose_offset.html.slim
- app/views/transcription_field/edit_columns.html.slim
- config/routes.rb
- db/migrate/20210325195823_add_offsets_to_transcription_field.rb
- db/migrate/20210325200811_add_row_highlight_to_transcription_field.rb
- db/schema.rb
Add a viewer to the spreadsheet data entry control for #2343
> 2343 viewer overlay

- lib/contentdm_translator.rb
> Handle v2 URIs for #2468

- app/views/shared/_handsontable.html.erb
This branch has code that adds a new row to the spreadsheet when a user reaches the last of the starting rows.  
To duplicate:
* Configure a spreadsheet with 4 initial rows
* Transcribe a page (you should see four rows in the spreadsheet)
* Move the cursor to the last row
* A fifth row should be added to the spreadsheet.
> NOT READY TO MERGE Add new row to spreadsheet when user selects last row for #2478

- lib/tasks/remediate_cdm_manifests.rake
> Task to remediate bad CDM URLs for #2512

- app/controllers/concerns/export_service.rb
> Promulgate headers/footers on spreadsheet exports #2508

- Gemfile
- Gemfile.lock
> Back-level omniauth as workaround for 2573

- app/controllers/application_controller.rb
- app/controllers/user_controller.rb
- app/views/layouts/application.html.slim
- config/routes.rb
> Added a locale switcher to the application header for #2559

- app/controllers/export_controller.rb
> Support Pandoc 2 instead of 1 for #2583

- app/controllers/application_controller.rb
> Add more logging to catch #2609

- app/controllers/concerns/export_service.rb
> Fix bulk export for #2616

- app/controllers/concerns/export_service.rb
> Include imported metadata in work export for #2567

- lib/contentdm_translator.rb
This fixes the root issue in #1678 but does not remediate any existing data.
> Bypass callbacks for #1678

- config/locales/dashboard/dashboard-en.yml
- lib/tasks/ingestor.rake
Import XML fragments in zip files.
> Import XML as well as OCR for #2562

- app/models/facet_config.rb
> Handle metadata values containing hashes for #2636

- config/locales/transcribe/transcribe-en.yml
- config/locales/transcribe/transcribe-es.yml
- config/locales/transcribe/transcribe-pt.yml
removed the <br> found in all 3 languages
> removed <br> for #2348

- app/views/dashboard/exports.html.slim
- config/locales/dashboard/dashboard-en.yml
This addresses one of the suggestions in #2656 but not all of them.
> Add configuration to export screen for #2656

- app/controllers/bulk_export_controller.rb
- app/controllers/concerns/export_service.rb
- app/helpers/export_helper.rb
- app/views/bulk_export/new.html.slim
- db/migrate/20210709234034_add_formats_to_bulk_export.rb
- db/schema.rb
This was requested by LVA, so we should notify Sonya when it is deployed
> Bulk export pdf docx

- app/controllers/concerns/export_service.rb
Addresses #2655.  Notify Rose B. when deployed.
> Export searchable pages

- app/controllers/concerns/export_service.rb
Fixes problem reported by TNI-UK
> Export failure case sensitivity

- app/helpers/export_helper.rb
> Remove parenthesis from delimiters for hierarchical subjects

- app/views/admin_mailer/collection_stats_by_owner.html.slim
- config/locales/admin_mailer/admin_mailer-en.yml
This is in emails so it needs testing.
> link to profile for #2648

- app/controllers/contact_controller.rb
- app/helpers/contact_helper.rb
- app/views/contact/form.html.slim
Rotates the email form parameter on a regular basis
> Rotate email param for #1853

- app/controllers/transcribe_controller.rb
> Check for logged out user on still_editing for #2062

- app/controllers/contact_controller.rb
- app/helpers/application_helper.rb
- app/helpers/contact_helper.rb
- app/views/static/software.html.slim
- config/routes.rb
Another attempt to address contact form spam in #1853
> Add parameter to link for #1853

- app/views/collection/_facet_form.html.slim
- app/views/static/software.html.slim
Skipped one of the reported issues; use this to argue against it:
https://github.com/dequelabs/axe-core/issues/1009
Also this is covered by our VPAT, as it's configuration for a feature that isn't going to be accessible.
> Accessibility fixes

- app/controllers/transcribe_controller.rb
> 2756 empty spreadsheet failure

- app/helpers/abstract_xml_helper.rb
- app/helpers/export_helper.rb
- app/views/export/facing_edition.html.erb
Handle and format metadata in PDF exports
> Better handling for metadata in #2863

- app/assets/javascripts/transcribe.js.erb
- app/assets/stylesheets/sections/article.scss
- app/views/article/edit.html.slim
- app/views/transcribe/display_page.html.slim
- app/views/transcribe/translate.html.slim
- config/locales/collection/collection.en.yml
Improve codemirror and dictation interoperation.
> 2738 dictation codemirror reprise

- app/controllers/transcription_field_controller.rb
- app/views/transcription_field/_metadata_field_layout.html.slim
- app/views/transcription_field/_new_field_form.html.slim
This fixes the ajax redirect problem.  I was not able to duplicate any problems with the multiselect displaying incorrectly or not loading options.
> 2801 metadata multiselect

- app/controllers/concerns/static_site_exporter.rb
- app/controllers/iiif_controller.rb
- app/models/collection.rb
- app/models/document_set.rb
- app/models/work.rb
- app/views/export/facing_edition.html.erb
- config/locales/collection/collection.en.yml
- db/migrate/20211206205128_add_searchable_metadata_to_work.rb
- db/schema.rb
Testing this will require a (fairly) long-running migration.
> Make metadata searchable for #2897

- lib/subject_details_exporter.rb
> Added articles to subject details export for #2900

- app/controllers/article_controller.rb
We should consider abstracting the Charlock test and using it everywhere we read a CSV file
> Fixes #2915 by detecting character encoding

- app/views/admin/edit_user.html.slim
- config/locales/admin/admin-en.yml
> Added Staff account type to admin user edit screen #2970

- db/migrate/20220322183841_widen_option_columns.rb
- db/schema.rb
This expands the options field for configuring spreadsheet drop-down/selects.
> Expand options column width for #3012

- app/helpers/export_helper.rb
> Escape ampersands on PDF export for #3044

- app/assets/stylesheets/sections/work.scss
- app/controllers/collection_controller.rb
- app/controllers/display_controller.rb
- app/views/collection/needs_transcription_pages.html.slim
- app/views/display/_pages_view.html.slim
- config/locales/display/display-en.yml
This is a partial solution to #2929
> If no pages need transcription, show incomplete pages for #2929 + CTA

- app/controllers/page_controller.rb
- app/views/display/_pages_view.html.slim
- app/views/work/pages_tab.html.slim
Updates from parameters and calls only stats callback.
> Be more thoughtful about callbacks for #2911

- app/models/work.rb
> Support numeric file uploads by prefixing slug for #3096

- app/views/user/update_profile.html.slim
I'm not sure this change is correct, but I can't figure out why I introduced this code 14 months ago:
https://github.com/benwbrum/fromthepage/blame/main/app/views/user/update_profile.html.slim#L5
> remove extraneous collection image title

- app/controllers/collection_controller.rb
- app/controllers/quality_samplings_controller.rb
- app/models/page.rb
- app/views/collection/user_contribution_list.html.slim
- app/views/quality_samplings/show.html.slim
- config/locales/collection/collection.en.yml
- config/locales/quality_samplings/quality_samplings.en.yml
- config/routes.rb
- lib/tasks/update_last_editor.rake
Completes approve-all functionality.
To-review: column contents after approve-all has been pressed.
> 3092 recalculate sample set

- app/controllers/abstract_xml_controller.rb
> Add additional stopwords to Autolink for #3194

- app/views/transcribe/_save_buttons.html.slim
To reproduce: http://localhost:3000/historyrevealed/shopping-stories-project/j-h-1773-1-230/transcribe/32177706
> Fixes #3227 by testing empty string as well as nil on page status

- app/controllers/sc_collections_controller.rb
- app/models/sc_canvas.rb
- app/models/sc_manifest.rb
- app/views/sc_collections/explore_manifest.html.slim
- db/migrate/20220718104413_add_annotations_to_sc_canvas.rb
- db/schema.rb
> Import annotation lists from IIIF manifests for #3219

- app/controllers/application_controller.rb
Although I've not been able to reproduce this, this logic might address (and hopefully resolves) #3293
> Refactor logic to address #3293

- app/controllers/transcription_field_controller.rb
> Fixed #3318 by saving page number on field config

- app/controllers/abstract_xml_controller.rb
This addresses the first problem in #3322.
Tests pass locally.
> Fixes initial skipping in autolink for #3322

- app/views/article/show.html.slim
- spec/features/document_sets_spec.rb
- spec/http-mocks/cdm/bad_iiif_manifest.yml
- spec/http-mocks/cdm/midpoint-repository.yml
- spec/http-mocks/cdm/midpoint-shelwater-collection.yml
- spec/http-mocks/cdm/midpoint-shelwater-item.yml
- spec/http-mocks/iiif/cambridge_hebrew_mss.yml
Temporarily disable subject-seeded text search for #3364
> Temporarily disable subject-seeded text search for #3364

- app/controllers/concerns/export_service.rb
Skips printing works with no pages.
> 3400 export printable no pages

- app/assets/javascripts/application.js
- app/views/layouts/application.html.slim
We need to test note creation and thredded functionality, then deploy and re-test thredded functionality to see if assets precompilation needs to be changed.
> Conditionally include thredded.js due to jquery_ujs conflict #3412

- Gemfile.lock
@benwbrum OK to create a PR for this?
> Fixes #3469 by updating newrelic agent gem

- app/views/admin/user_list.html.slim
Definitely let me know if the order of the links needs to be different or if this needed to be approached another way, thanks!
For #3415
> login as transcriber addition

- app/controllers/admin_controller.rb
- app/views/admin/owner_list.html.slim
- app/views/admin/user_visits.html.slim
- config/locales/admin/admin-en.yml
Changes owner list order and adds a visit link.
> Change owner list order for #3521

- app/controllers/export_controller.rb
To reproduce: open a work with downloadable content.  Press the MS Word or PDF download buttons.
> Fixed bad number of arguments error for #3545

- app/overrides/controllers/thredded/preferences_controller_override.rb
- app/views/thredded/topics/edit.html.erb
- config/initializers/thredded.rb
Closes #3541 #3542 #3543 #3544
> 3541 multi tenant forum fixes

- app/models/collection.rb
> Fixes #3498 by using cached deed update date

- app/views/export/tei.html.erb
> Change old url_for to root_url for #3577

- app/controllers/bulk_export_controller.rb
- app/models/bulk_export.rb
- app/views/bulk_export/show.html.erb
> Handle datatypes correctly for #3591 and #3594

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- config/database.yml
- config/environments/development.rb
This adds configuration for [GitHub codespaces](https://github.com/features/codespaces).
> Add codespaces

- app/helpers/export_helper.rb
> Fixes #3650 by escaping category titles

- db/migrate/20230522121402_add_created_at_desc_index_to_deeds.rb
- db/schema.rb
This redoes the indexes on the `deeds` table from scratch.
Closes #3008 #3439 #2378 #1976
> Reindex the deed table for #3439 #3008 #2378 #1976

- app/helpers/abstract_xml_helper.rb
- spec/helpers/abstract_xml_helper_spec.rb
- spec/http-mocks/cdm/bad_iiif_manifest.yml
- spec/http-mocks/cdm/midpoint-repository.yml
- spec/http-mocks/cdm/midpoint-shelwater-collection.yml
- spec/http-mocks/cdm/midpoint-shelwater-item.yml
- spec/http-mocks/iiif/cambridge_hebrew_mss.yml
> Sanitize output for #3656

- app/helpers/abstract_xml_helper.rb
- spec/helpers/abstract_xml_helper_spec.rb
- spec/http-mocks/cdm/bad_iiif_manifest.yml
- spec/http-mocks/cdm/midpoint-repository.yml
- spec/http-mocks/cdm/midpoint-shelwater-collection.yml
- spec/http-mocks/cdm/midpoint-shelwater-item.yml
- spec/http-mocks/iiif/cambridge_hebrew_mss.yml
> Produce valid XML for #3660

- app/helpers/application_helper.rb
- app/models/sc_manifest.rb
- app/views/sc_collections/explore_manifest.html.slim
- config/locales/sc_collections/sc_collections-de.yml
- config/locales/sc_collections/sc_collections-en.yml
- config/locales/sc_collections/sc_collections-es.yml
- config/locales/sc_collections/sc_collections-pt.yml
> Handle multi-lingual IIIF manifest descriptions for #3663

- app/controllers/concerns/export_service.rb
- app/controllers/export_controller.rb
- app/helpers/export_helper.rb
- app/views/export/facing_edition.html.erb
Closes #3692 
(See issue for testing notes)
> Fixes #3692 by respecting print configuration in facing edition view

- app/models/work.rb
> Only delete images that aren't being used for #3707

- lib/tasks/weekly_trial_cohort.rake
> Fix greater than error for #3643

- app/controllers/concerns/export_service.rb
> Treat header fields as field-based rather than markdown tables for #3721

- lib/tasks/weekly_transcriber_cohort.rake
- lib/tasks/weekly_trial_cohort.rake
> Track contributor success metrics for #2815

- app/mailers/admin_mailer.rb
- lib/tasks/weekly_transcriber_cohort.rake
> Fix mail subject for #2815

- db/migrate/20230620133502_set_created_by_for_articles.rb
> Fix bad migration in deployment branch

- db/migrate/20230912135655_add_index_to_work_statistics.rb
- db/schema.rb
> Add index to work statistics for #3780

- app/controllers/statistics_controller.rb
- app/models/collection_statistic.rb
- app/models/owner_statistic.rb
- app/views/dashboard/summary.html.slim
- app/views/statistics/_collaborators.html.slim
- app/views/statistics/collection.html.slim
- config/locales/statistics/statistics-de.yml
- config/locales/statistics/statistics-en.yml
- config/locales/statistics/statistics-es.yml
- config/locales/statistics/statistics-fr.yml
- config/locales/statistics/statistics-pt.yml
- db/migrate/20230914142257_revise_index_on_page_works.rb
- db/schema.rb
> 3712 reviewers on leader board

- app/models/collection_statistic.rb
- app/views/deed/_deeds.html.slim
- db/migrate/20230914142257_revise_index_on_page_works.rb
- db/schema.rb
> Address performance for #3786

- app/controllers/concerns/export_service.rb
- app/helpers/export_helper.rb
- app/models/page.rb
- app/models/xml_source_processor.rb
> Added spreadsheet exports to PDFs for #3720

- app/helpers/export_helper.rb
> Preserve linebreaks in printable formats

- app/controllers/collection_controller.rb
- app/models/document_set.rb
- app/views/collection/edit.html.slim
- config/locales/collection/collection-de.yml
- config/locales/collection/collection-en.yml
- config/locales/collection/collection-es.yml
- config/locales/collection/collection-fr.yml
- config/locales/collection/collection-pt.yml
- db/migrate/20231006175743_add_alphebetize_works_to_collection.rb
- db/schema.rb
> Offer an option for ordering works alphabetically for #3810

- app/models/article.rb
> Fixes #3831 by always processing source text.

- app/models/metadata.rb
> 3834 upload work description

- app/assets/javascripts/textdiff/jquery.table-diff.js
> #2771 improve the usability of version comparison screen

- app/controllers/concerns/export_service.rb
> #2519 include marked as blank pages in csv

- lib/tasks/transkribus_processing.rake
- lib/transkribus/page_processor.rb
> Refactor rake task for Transkribus API integration

- app/controllers/page_controller.rb
- app/views/shared/_osd_div.html.slim
> Don't show alto for metadata entry #3875

- app/controllers/page_controller.rb
- lib/tasks/transkribus_processing.rake
- lib/transkribus/page_processor.rb
> Don't convert XML to JSON for #3880

- lib/transkribus/page_processor.rb
> Force encoding of Transkribus ALTO to UTF-8 #3885

- app/views/shared/_osd_div.html.slim
> Add copy/unlock buttons for #3887

- app/controllers/dashboard_controller.rb
- app/models/collection.rb
- app/views/dashboard/watchlist.html.slim
- config/locales/dashboard/dashboard-de.yml
- config/locales/dashboard/dashboard-en.yml
- config/locales/dashboard/dashboard-es.yml
- config/locales/dashboard/dashboard-fr.yml
- config/locales/dashboard/dashboard-pt.yml
> changes in collaborator dashboard

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- app/controllers/application_controller.rb
- config/environments/development.rb
This fixes a couple of errors that were preventing the Codespaces environment from working correctly.
Initial setup was in #3627.
> Fixed Codespaces environment

- app/views/search_attempt/show.html.slim
- config/locales/search_attempt/search_attempt-de.yml
- config/locales/search_attempt/search_attempt-en.yml
- config/locales/search_attempt/search_attempt-es.yml
- config/locales/search_attempt/search_attempt-fr.yml
- config/locales/search_attempt/search_attempt-pt.yml
> Refactor search attempt show for #3900

- config/database.yml
- config/environments/production.rb
> dev to ftp

- app/views/shared/_codemirror.html.erb
- lib/openai/text_normalizer.rb
- lib/tasks/ai_plaintext_generator.rake
> Fix issues in ChatGPT-based HTR post-processing for #3904

- app/helpers/abstract_xml_helper.rb
- app/views/display/_pages_view.html.slim
> Refactor highlight code to support bulk exports for #3906

- app/controllers/iiif_controller.rb
- app/models/ia_leaf.rb
- spec/http-mocks/iiif/imports_iiif_manifests.yml
> Update IIIF URLs at the Internet Archive for #3913

- config/routes.rb
- spec/features/display_marked_as_blank_spec.rb
Prevent cached URLs in crawlers from hitting very slow action.
> Change URL for deed list

- app/controllers/collection_controller.rb
- app/helpers/quality_samplings_helper.rb
- app/views/quality_samplings/show.html.slim
> #3917 solved statistics were not being recalculated after bulk approval

- app/models/page.rb
- app/models/page_version.rb
- app/views/page_version/show.html.slim
> #3921 don't log a version or time if a page hasn't changed

- lib/image_helper.rb
> Resolves #3945 by passing parameter to block

- app/models/page.rb
> Use absolute urls for locally hosted page images for #3889

- app/controllers/admin_controller.rb
- app/views/admin/show_tag.html.slim
Addresses #3839 by improving duplicate matching and adding edit/delete buttons to tag show view.
> Improve tag view usability for #3839

- app/controllers/bulk_export_controller.rb
- app/views/export/facing_edition.html.erb
- config/locales/bulk_export/bulk_export-de.yml
- config/locales/bulk_export/bulk_export-en.yml
- config/locales/bulk_export/bulk_export-es.yml
- config/locales/bulk_export/bulk_export-fr.yml
- config/locales/bulk_export/bulk_export-pt.yml
> Add new message and fix route for #3953

- app/controllers/dashboard_controller.rb
- app/helpers/dashboard_helper.rb
- app/views/dashboard/your_hours.html.slim
> Fixes #3973 by reflecting projects a user worked on

- app/controllers/static_controller.rb
> fixes #3988

- app/views/collection/show.html.slim
Does not close #3991 -- stopgap only.
> Disable full-text search for large collections as stopgap for #3991

- lib/tasks/transkribus_processing.rake
> Add finer-grained tasks for Transkribus processing

- app/assets/stylesheets/components/layout.scss
- app/assets/stylesheets/sections/collection.scss
- app/views/collection/edit.html.slim
- app/views/collection/edit_danger.html.slim
- app/views/collection/edit_help.html.slim
- app/views/collection/edit_look.html.slim
- app/views/collection/edit_privacy.html.slim
- app/views/collection/edit_quality_control.html.slim
- app/views/collection/edit_tasks.html.slim
- app/views/layouts/application.html.slim
> Fixes #4012 by relocating overflow:auto to a new wrapper div

- app/controllers/concerns/export_service.rb
> #4015 Add color to hyperlinks in exported PDF files

- app/helpers/dashboard_helper.rb
> Fixes #4023 by filtering volunteer hours on correct column

- app/views/collection/show.html.slim
> Reenable full-text search for large collections #3991

- app/views/shared/_handsontable.html.erb
> Freeze spreadsheet header during scroll for #3002

- app/controllers/api/v1/bulk_export_controller.rb
- config/locales/dashboard/dashboard-de.yml
- config/locales/dashboard/dashboard-en.yml
- config/locales/dashboard/dashboard-es.yml
- config/locales/dashboard/dashboard-fr.yml
- config/locales/dashboard/dashboard-pt.yml
> Add subject details csv export to bulk export API for #4035

- app/views/shared/_handsontable.html.erb
> Higlight cells in yellow on load for #3001

- Gemfile.lock
- lib/openai/description_tagger.rb
> Upgrade and refactor OpenAI client for #4058

- app/models/external_api_request.rb
- lib/tasks/transkribus_processing.rake
- lib/transkribus/page_processor.rb
> Handle document sets for #4056

- app/models/user.rb
- app/views/admin/uploads.html.slim
- lib/tasks/ingestor.rake
Addresses #4010 but does not close it.
> Add associations to User for #4010

- app/views/shared/_handsontable.html.erb
> Fix page reload spreadsheet headers for #3002

- app/controllers/concerns/export_service.rb
> Modify export code for multiple spreadsheets and error in #4054

- app/views/shared/_handsontable.html.erb
- app/views/transcribe/display_page.html.slim
> Fix JS error on image layout changes for #4066

- app/controllers/transcribe_controller.rb
- app/views/shared/_codemirror.html.erb
- app/views/shared/_handsontable.html.erb
- app/views/transcribe/display_page.html.slim
- config/routes.rb
Closes #4069
Note that this does not yet include code for field-based projects.
> Track active editing for volunteer hours #4069

- app/views/transcribe/translate.html.slim
> Fixes JS error on translation page introduced by #4069

- CONTRIBUTING.md
> Add CONTRIBUTING.md for #4085

- app/views/shared/_osd_div.html.slim
> Add event handler for #4053

- app/controllers/dashboard_controller.rb
- app/models/tag.rb
- app/views/dashboard/browse_tag.html.slim
- app/views/dashboard/new_landing_page.html.slim
Addresses #3839 but needs more usability testing.
> Make tag cloud listings consistent for #3839

- app/assets/stylesheets/sections/page.scss
> Fixed bad field alignment on long labels

- app/views/shared/_codemirror.html.erb
> add head tag to codemirror #2696

- app/views/shared/_osd_div.html.slim
> #4086 fix JS error clicking code mirror

- Gemfile
- Gemfile.lock
- config/initializers/rack_attack.rb
Closes #4124 
Note that this may need additional configuration after we deploy.  Post-deployment monitoring is advised.
> 4124 rack attack scraper defense

- app/models/page.rb
- config/application.rb
- config/initializers/rack_attack.rb
> Throttle bots for #4130

- config/initializers/rack_attack.rb
> 4130 block bots

- config/application.rb
- config/initializers/rack_attack.rb
> Refine initialization for #4130

- app/assets/javascripts/transcribe.js.erb
- config/locales/collection/collection-de.yml
- config/locales/collection/collection-en.yml
- config/locales/collection/collection-es.yml
- config/locales/collection/collection-fr.yml
- config/locales/collection/collection-pt.yml
> Voice dictation for Codemirror 

- app/assets/javascripts/transcribe.js.erb
- config/locales/collection/collection-de.yml
- config/locales/collection/collection-en.yml
- config/locales/collection/collection-es.yml
- config/locales/collection/collection-fr.yml
- config/locales/collection/collection-pt.yml
It is branched off 4003-fix-voice-dictation.
Closes #2681
> 2681 voice dictation subject

- app/assets/stylesheets/components/shared.scss
- app/views/document_sets/index.html.slim
> 2531 - responsive table CSS on document sets page

- app/assets/javascripts/textdiff/jquery.table-diff.js
- app/assets/stylesheets/components/shared.scss
- app/views/page_version/show.html.slim
> 2743 version tab

- app/assets/javascripts/application.js
> 3569 - fix double confirm popup

- app/assets/stylesheets/plugins/splitter.scss
- app/assets/stylesheets/sections/page.scss
- app/views/display/display_page.html.slim
- app/views/shared/_handsontable.html.erb
- app/views/transcribe/display_page.html.slim
> 4191 columns disappear

- app/assets/stylesheets/sections/page.scss
- app/controllers/work_controller.rb
- app/views/shared/_osd_div.html.slim
- config/routes.rb
> 4194 fix OSD viewer issue on metadata page

- app/assets/stylesheets/sections/page.scss
- app/controllers/work_controller.rb
- app/views/shared/_osd_div.html.slim
- config/routes.rb
> 4194 fix OSD viewer issue on metadata page (#4198)

- app/assets/stylesheets/sections/article.scss
- app/assets/stylesheets/sections/page.scss
- app/views/shared/_handsontable.html.erb
- app/views/transcribe/display_page.html.slim
- app/views/transcription_field/_field_layout.html.slim
> 4202 scrolling ttb mode

- app/assets/stylesheets/sections/article.scss
- app/assets/stylesheets/sections/page.scss
- app/views/shared/_handsontable.html.erb
- app/views/transcribe/display_page.html.slim
- app/views/transcription_field/_field_layout.html.slim
* 4202 fix scrolling css issues
* 4202 fixed toolbar height
> Dev into deployment

- app/controllers/transcribe_controller.rb
- app/models/deed.rb
- app/models/external_api_request.rb
- app/models/page.rb
- db/migrate/20240710132602_mitigate_incomplete_review.rb
- db/schema.rb
- spec/features/archive_import_spec.rb
- spec/features/needs_review_spec.rb
- spec/http-mocks/cdm/bad_iiif_manifest.yml
- spec/http-mocks/cdm/midpoint-repository.yml
- spec/http-mocks/cdm/midpoint-shelwater-collection.yml
- spec/http-mocks/cdm/midpoint-shelwater-item.yml
> 4209 Don't mark pages incomplete when you review them

- app/controllers/transcribe_controller.rb
- app/views/transcribe/_save_buttons.html.slim
- config/locales/transcribe/transcribe-de.yml
- config/locales/transcribe/transcribe-en.yml
- config/locales/transcribe/transcribe-es.yml
- config/locales/transcribe/transcribe-fr.yml
- config/locales/transcribe/transcribe-pt.yml
- spec/features/document_sets_spec.rb
> 4221 Fix accidental approve to needs-review pages

- app/controllers/notes_controller.rb
- app/models/note.rb
> Use destroy instead of delete for notes #4238

- lib/contentdm_translator.rb
> 4229 Added new CDM parser for versionless manifest URIs

- app/assets/stylesheets/codemirror/lib/codemirror.css
> 4252 fixed z-index issue in subject autocomplete

- app/assets/javascripts/application.js
- app/views/shared/_handsontable.html.erb
- app/views/transcribe/display_page.html.slim
> 4243 fix spreadsheet header lose when scrolling

- app/views/shared/_bento_chat.html.erb
> Handle logged out users for #4265

- app/assets/javascripts/application.js
- app/helpers/abstract_xml_helper.rb
> 4236 fix missing subject popup

- app/controllers/work_controller.rb
- app/views/work/describe.html.slim
- app/views/work/metadata_overview.html.slim
> 4280 fix slider hides metadata issue

- app/views/article/edit.html.slim
- app/views/shared/_codemirror.html.erb
- app/views/shared/_insert_table_modal.html.erb
- app/views/transcribe/display_page.html.slim
- app/views/transcribe/translate.html.slim
> 4282 made subject description field to codemirror

- app/helpers/abstract_xml_helper.rb
> #4334 add title to all anchor exports

- app/models/page.rb
- spec/models/page_spec.rb
> #4344 encode filenames for URLs

- app/controllers/application_controller.rb
- app/models/article.rb
- app/models/xml_source_processor.rb
- lib/tasks/remediator.rake
- spec/features/zz_deletion_spec.rb
- spec/http-mocks/cdm/bad_iiif_manifest.yml
- spec/http-mocks/cdm/midpoint-repository.yml
- spec/http-mocks/cdm/midpoint-shelwater-collection.yml
- spec/http-mocks/cdm/midpoint-shelwater-item.yml
- spec/http-mocks/iiif/cambridge_hebrew_mss.yml
Addresses but does not close #4269
> Log article deletions for #4269

- app/views/shared/_handsontable.html.erb
> 4359 fixed comment issue on date field spreedsheet

- app/controllers/admin_controller.rb
- app/views/admin/_collection_list_datatable.html.slim
- app/views/admin/edit_tag.html.slim
- config/routes.rb
Addresses (but does not close) #3839
> Add new tag tools for #3839

- app/helpers/transcribe_helper.rb
- app/models/ia_leaf.rb
- public/images/ia_cache/README
- spec/models/page_spec.rb
> Cache IA-hosted images for #4408

- app/views/shared/_codemirror.html.erb
- spec/features/export_spec.rb
- spec/features/forum_spec.rb
> 4431 fix rows insert in markdown table

- app/assets/stylesheets/application.scss
> 4427 hide th.bang header

- app/assets/javascripts/ftp_interface.js
- spec/features/export_spec.rb
- spec/features/forum_spec.rb
> 4426 fixed codemirror button group top position in ttb layout mode

- app/helpers/transcribe_helper.rb
- app/models/sc_canvas.rb
> 4458 Correct tilesource for v3 manifests

- app/models/sc_canvas.rb
Workaround for NARA-specific problem in #4458
> Add NARA workaround for #4458

- app/helpers/export_helper.rb
> Reorganize TEI export for child categories #4475

- app/models/sc_canvas.rb
> Fix info.json URL for AM Quartex images #4490

- app/controllers/concerns/export_service.rb
- app/helpers/export_helper.rb
- app/models/page.rb
- lib/tasks/bulk_export.rake
- spec/models/page_spec.rb
> Fix #4518 by using better URL encoding

- app/assets/javascripts/ftp_interface.js
> 4494 fixed slider broken for image-on-top

- app/models/document_set.rb
- app/models/page.rb
- config/initializers/01fromthepage.rb
- db/schema.rb
- lib/elastic/schema/template.json
- lib/elastic/schema/work.json
* ES: Don't drop terms at querytime for identifier analysis
* Fix is_public and initializer falsiness
---------
> Search branch patch (#4545)

- app/controllers/application_controller.rb
- app/models/user.rb
> Fix #4555 to let users transcribe private docs

- app/helpers/abstract_xml_helper.rb
> Fixes #4551 accidental rendering of footers

- app/views/export/show.html.erb
> Clean up HTML export contributors and links for #1557 #4557

- app/models/collection.rb
- app/models/page.rb
- app/models/work.rb
> give staff access in ES queries

- app/controllers/deed_controller.rb
- spec/features/display_marked_as_blank_spec.rb
* Disable public deed listing for #4601
* Attempt to fix test failure
> Disable public deed listing for #4601 (#4602)

- app/assets/stylesheets/sections/collection.scss
- app/controllers/article_controller.rb
- app/controllers/category_controller.rb
- app/models/article.rb
- app/models/category.rb
- app/views/article/edit.html.slim
- app/views/article/list.html.slim
- app/views/article/show.html.slim
- app/views/category/_form.html.slim
- app/views/export/tei.html.erb
- config/locales/article/article-de.yml
- config/locales/article/article-en.yml
- config/locales/article/article-es.yml
- config/locales/article/article-fr.yml
- config/locales/article/article-pt.yml
- config/locales/category/category-de.yml
- config/locales/category/category-en.yml
- config/locales/category/category-es.yml
- config/locales/category/category-fr.yml
- config/locales/category/category-pt.yml
- config/routes.rb
- db/migrate/20250411161011_add_org_fields_to_articles.rb
- db/migrate/20250411162248_add_org_fields_enabled_to_categories.rb
- db/schema.rb
- lib/tasks/cwgk_migrate.rake
- spec/i18n_spec.rb
- spec/requests/category_controller_test.rb
> Add organization fields for #4609

- lib/tasks/cwgk_migrate.rake
> Fixes #4639 and #4641

- Gemfile
- Gemfile.lock
- app/interactors/application_interactor.rb
- app/interactors/database/base.rb
- app/interactors/database/export/dump_builder.rb
- app/interactors/database/import/dump_ingestor.rb
- app/models/collection.rb
- app/models/collection_block.rb
- app/models/collection_collaborator.rb
- app/models/collection_reviewer.rb
- app/models/collection_tag.rb
- lib/tasks/database.rake
- spec/interactors/database/export/dump_builder_spec.rb
- spec/interactors/database/import/dump_ingestor_spec.rb
* 4464 - Collection data export task
* 4644 - Fix typo in model
* 4644 - Add assets to export process
* 4644 - Fix specs
* 4644 - Add import task
> 4644 - Collection data export task (#4645)

- app/controllers/masquerades_controller.rb
- app/views/admin/visit_actions.html.slim
Closes #4471
Addresses one item from #4010
> 4010 4474 small annoyances

- app/assets/stylesheets/base/global.scss
- app/helpers/abstract_xml_helper.rb
- app/views/shared/_codemirror.html.erb
> Support PB and CB tags for #2224 #2935

- app/controllers/article_controller.rb
- spec/requests/article_controller_spec.rb
> Change from send_file to render to fix #4705 in production

- app/helpers/export_helper.rb
> added date and time to each document export

- app/controllers/collection_controller.rb
- app/controllers/notes_controller.rb
- app/helpers/contributor_helper.rb
- app/views/collection/_contributors_body.html.slim
- app/views/notes/discussions.html.slim
- config/routes.rb
- lib/tasks/collection_copy.rake
- spec/requests/notes_controller_spec.rb
…#4746)
* Initial plan
* Fix 500 error in notes discussions by handling nil notes gracefully
---------
> dev into deployent
